### PR TITLE
feat(datepicker) : add select week functionality

### LINKED ISSUE #4921: feature(datepicker): Add some way to select a week
### Feature request:
I'm looking for the ability to select a week number, but I can't seem to find a way to do this right now. The week numbers are displayed, but are not clickable. When clicked, I'd suggest to select the first day of the week as output.

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 3.1.3
Angular: 7.1.2
Bootstrap: 3.3.7

### PR DESCRIPTION
**Pull request by daniloff200**
closes #4921 

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by dmitry-zhemchugov** [comment]
Tested. Works as expected.

**Review by Domainv — CHANGES_REQUESTED** [review]
Needs to add test for the functionality

**Comment by ludmilanesvitiy** [comment]
1. Default Datepicker placeholder in the first input confuse the user, because it's not default datepicker, it's datepicker with selectWeek:true 
screenshot from 2019-01-17 12-53-39
2. Not need to change any other config properties, need to support rule: *Each Demo show only 1 specific usage of config property. Only Demo for changing default config could contain more than 1 changed property*
I mean dateInputFormat:  and containerClass:

**Review by Domainv — APPROVED** [review]

**Comment by dmitry-zhemchugov** [comment]
1. First input for Datepicker contains text: "Datepicker with select week"
datepicker

2. Not changed any other config properties, like "dateInputFormat:" and "containerClass:"

3. All Travis CI tests are passed.

Feature work as expected, nothing of other functionality doesn't crashed.
Ready to merge.

**Pull request merged**
