### PR TITLE
fix(Typeahead) highlight displays <strong> tag when empty spaces added at the end of query and does not escape html tags

### PR DESCRIPTION
**Pull request by UdayAppam**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by UdayAppam** [comment]
https://github.com/valor-software/ngx-bootstrap/issues/4350
Could you please review and if any suggestions open to discuss

**Comment by UdayAppam** [comment]
Hi @[valorkin](https://github.com/valorkin)
Could you please review these changes.

**Comment by matthewfedak** [comment]
Is there any update to this issue? Can happily offer a reward to the person who gets this merged.

**Comment by rohanahata** [comment]
@valorkin can you please let us know if this can be merged?

**Pull request merged**
