### PR TITLE
fix(datepicker): skip years reordering if minMode='year'

### PR DESCRIPTION
**Pull request by livthomas**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [X] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [X] built and tested the changes locally.
 - [X] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

This PR is fixing issue #5154.

### CODE REVIEW

**Comment by daniloff200** [comment]
looks like #5166 can be also fixed with this PR

**Comment by livthomas** [comment]
@daniloff200 It seems like `should select a week, when selectWeek flag is true` fails even without my changes. Where is the problem?

**Comment by daniloff200** [comment]
@livthomas it's a random racing issue with this test, it sometimes fails, I don't think, that your changes related to weeks select functionality & e2e's

**Comment by Domainv** [comment]
As I see it requires a fix

**Comment by livthomas** [comment]
@Domainv The problem should be fixed now.

**Comment by daniloff200** [comment]
@livthomas  looks like, some tests are failed, and it's not some random stuff. Can you please try to look on it?

**Comment by daniloff200** [comment]
I've also updated your branch with the latest dev

**Comment by livthomas** [comment]
@daniloff200 The tests are fixed now. The problem was with undeterministic behavior of years calendar model. The tests relied on the model based on current year but it is sometimes different (shifted by two years). So I changed them to get the first date in the calendar model from the initial state.

**Comment by daniloff200** [comment]
@livthomas  I see one lint issue, and also, tests are still faiilin' :(

**Comment by livthomas** [comment]
@daniloff200 The tests run in the CI gave slightly different results than the tests run locally on my machine. But it should be fixed now.

**Review by Domainv — APPROVED** [review]

**Comment by daniloff200** [comment]
:man_dancing:  :man_dancing: :man_dancing: :man_dancing:

**Pull request merged**
