### PR TITLE
 feat(typeahead) stop selecting first result when displaying matches 

### LINKED ISSUE #3965: feat:typeahead Don't select any fields until the first up/down arrow keypress
We've been having problems with the typeahead behavior introduced in https://github.com/valor-software/ngx-bootstrap/pull/2839 in conjunction with setting `minLength` to 0.

Due to the above feature, when a typeahead has a `minLength` of 0, when keyboard / screen reader users Tab from field to field, as they go through the typeahead field they unintentionally select the first item from the list.

Disabling the select on Tab feature as outlined in #3842 would be one way to fix the issue, but we _do_ like the idea behind the feature, and we think that a fairly minimal change in behavior could allow keeping the feature around while also improving the experience for keyboard users.

Our proposal is to change the initial state when the typeahead dropdown menu is first shown, so that rather than the first item being active and selected on Enter/Tab, no items are active until the first up/down arrow keypress, and so enter/tab would not select anything until then.

Would this be a welcome change? Would this be a desired default behavior or an optional one?

We're very interested in this feature (or something similar) and/or #3842, and would be happy to implement the feature ourselves, especially if it would be welcomed by the project maintainers.

### LINKED ISSUE #5061: typeaheadSelectFirstItem should not show first item as selected when set to false
### Bug description or feature request:

See attached screenshot. First item is selected but pressing enter does not select the first item. This is non-intuitive. Instead, nothing should be selected when typeaheadSelectFirstItem is set to false, and user can press down and enter to select. Related to https://github.com/valor-software/ngx-bootstrap/pull/4631 and https://github.com/valor-software/ngx-bootstrap/issues/3965

angular bootstrap 2019-02-13 09-40-56

### Plunker/StackBlitz that reproduces the issue:
See https://valor-software.com/ngx-bootstrap/#/typeahead#selected-first-item

### PR DESCRIPTION
**Pull request by maurizi**
The main intent behind this feature is to improve the user experience for navigating through the an application with keyboard while using a typeahead with `[typeaheadMinLength]="0"` .

To do so, I changed the way that active items are selected via the keyboard, requiring that up/down arrows be pressed before an item is active and can be selected with tab/enter.

Without this feature, tabbing through a typeahead with `minLength` set to 0 will on the first tab select the first item, and then on the second tab move to the next field.

I also added a few other items as well:
 - Fixed a few comment typos
 - Added a `typeaheadMinLength` example to the documentation.

Update: added option IsFirstItemActive/typeaheadIsFirstItemActive to activate the behavior

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [ ] added/updated API documentation.
 - [x] added/updated demos.

Closes #3965
Closes #5061

### CODE REVIEW

**Review by frickt — APPROVED** [review]

**Comment by maurizi** [comment]
@frickt thanks for the prompt review!

I saw that this test failed on TravisCI (which is a little confusing to me since I didn't make changes to the Timepicker):
```
HeadlessChrome 0.0.0 (Linux 0.0.0) Runtime coverage. Utils: Timepicker isInputLimitValid method should validate input according to the min limit and return false FAILED
```
Anything I need to do?

**Comment by frickt** [comment]
Nice change. I would need it as well.

May be you should consider using:
`/** if false the first match automatically will not be focused as you type */`
`// @Input() protected typeaheadFocusFirst:boolean;`
defaults to true, so that you don't change the current behaviour.

**Comment by YevheniiaMazur** [comment]
@IlyaSurmay , please, fix failed unit tests
Otherwise tested, looks good

**Comment by maurizi** [comment]
@YevheniiaMazur @IlyaSurmay I rebased this on the latest `development` and the tests are passing now.

**Comment by valorkin** [comment]
Hey thanks for PR!
Funnies part, that selecting first item with mig length zero was a request too :D

**Comment by valorkin** [comment]
it could be a breaking change,
in general I am agree with your idea,
give me some time to think about it

**Comment by calebeno** [comment]
We're currently switching from uib-bootstrap to ngx-boostrap (doing a hybrid conversion process from ng1 to ng2+).  In uib-bootstrap [typeahead](https://github.com/angular-ui/bootstrap/tree/master/src/typeahead), they have the option to `typeahead-focus-first` which determines whether or not the first item is selected as you type in the input field.  Having this option or similar would be really helpful.  For the moment, I took the code from this PR and wrapped the ngx typeahead in a custom directive to overwrite the functionality.  It works but is definitely a hacky solution.

**Comment by maurizi** [comment]
@frickt @calebeno I can see the reason behind wanting to switch this behavior on/off, though I would argue that it never makes sense to focus & select on the first item when `[minLength]="0"` and the input is empty, as it makes tabbing past the typeahead input w/ the keyboard without selecting a field impossible.

Perhaps even if `typeaheadFocusFirst` gets added it should only make an item active when the input has at least 1 character?

**Review by frickt — DISMISSED** [review]

**Review by KK4ito — DISMISSED** [review]

**Comment by calebeno** [comment]
@maurizi Any updates on this?

**Comment by maurizi** [comment]
@calebeno I'm happy to make any changes needed to get this merged, I'm still waiting on feedback from @valorkin

**Comment by valorkin** [comment]
Sorry folks, I was preparing https://ngtalks.io
I am merging PRs but not as fast as I want :(

**Comment by Liahus3003** [comment]
Is this feature available as of now ? It would be really useful to have it @valorkin

**Comment by maurizi** [comment]
Still waiting on @valorkin

**Comment by hassanasad** [comment]
@valorkin Can you please review this PR :) Its something lots of people are anxiously waiting on

**Comment by labrada83** [comment]
Any updates on this?

**Comment by ekwebster** [comment]
Needs this bad, any progress @valorkin?

**Comment by chubbard** [comment]
What's the hold up here?  We need this feature to fix the broken TAB behavior.

**Comment by hassanasad** [comment]
I love bootstrap typeahead component. However because @valorkin is super busy, i had to move onto Angular material autocomplete. Its quite simple to implement and works quite good. ( https://material.angular.io/components/autocomplete/examples ) Hope it unblocks some users.

**Comment by hisham** [comment]
+1. Would be great if this can be merged.

**Comment by maurizi** [comment]
Looks like @valorkin decided to merge a different PR to fix this instead.....

**Comment by ludmilanesvitiy** [comment]
Auto-tests passed, need to recheck existed functionality and rel issues.

**Comment by ludmilanesvitiy** [comment]
Functionality retested once more, looks good.

**Review by Domainv — APPROVED** [review]

**Pull request merged**
