### PR TITLE
fix(tooltip): disable pointer events

### PR DESCRIPTION
**Pull request by luciomartinez**
Disable pointer events to prevent tooltip flickering on mouse hover.

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by luciomartinez** [comment]
Thanks to @rokdazone at #3075

**Comment by Domainv** [comment]
pointer-events: none; - In IE10 does not work

**Comment by luciomartinez** [comment]
Better supporting something that none at all ¯\_(ツ)_/¯

**Comment by luciomartinez** [comment]
I really hope latest versions have this fixed.

g60

**Pull request closed without merging**
