### PR TITLE
feat(datepicker): add ability to use min mode correctly in daterangepicker

### LINKED ISSUE #5006: bsDaterangepicker doesn't work with minMode 'month'
Clicking in left datepicker do nothing but clicking in right datepicker somehow increase year.
```
<input type="text" bsDaterangepicker [bsConfig]="{minMode: 'month'}">
```
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.1.4

Angular: 7.1.4

Bootstrap: 4.1.3

### PR DESCRIPTION
**Pull request by daniloff200**
closes #5006

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by zaniniflz** [comment]
Hi,
How many time do you think we'll be able to use this feature?

**Comment by daniloff200** [comment]
@zaniniflz  Well, I've finished with initial functionality, but, I haven't implemented in range styles for years and months (like we have such grey lines for days). I hope to look at it this week, also, we have some other PRs to test/merge, and, it will be pretty enough to release a 6.0.1

As I said, I hope, it will be in next 10-15 days

also, I have a question.
Does your app, when you want to use it, works witn Angular 9 or 10? Because, 6+ versions of ngx-bootstrap does not compatible with Angular 8

**Comment by daniloff200** [comment]
UPD: I've worked on range styles, and, with years/ months it looks really not cool, and also, a lot of issues with alignment are appeared.

Basically, for example, the month view will look like this:

Selection_056


And, with range styles, like this:
Selection_057


So, maybe, it's better to left it, as it is

Thoughts, @zaniniflz ?

**Comment by zaniniflz** [comment]
@daniloff200, first of all thank you for your effort and commitment.
I'm using angular 9.
For me, as it is, it's very good.
I would be very happy to use it the way you showed me screeenshots

**Comment by juanMmartinez1** [comment]
any update?

**Review by IraErshova — APPROVED** [review]

**Comment by daniloff200** [comment]
Available in 6.1.0, it was released today

**Pull request merged**
