### PR TITLE
Allow modals for templates with context

### PR DESCRIPTION
**Pull request by julianseeger**
Currently, when calling modalService.show with a TemplateRef, the initialState is ignored.
With this change, the template gets its context and code like the following is possible:
```HTML
... (click)="openModal(template, {someproperty: 'with value'})"...

<ng-template #template let-someproperty="someproperty">
    {{someproperty}}
</ng-template>
```

**edit:** is there any interest in this change?

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by valorkin** [comment]
Looks good to me :)

**Review by daniloff200 — APPROVED** [review]

**Comment by daniloff200** [comment]
I've tried case with this code, and pass data to the modal, got an error 

Here's the modal code: 

 

```
<button type="button" class="btn btn-primary" (click)="openModal(template, {somedata: 'value'})">Create template modal</button>
  <ng-template #template let-somedata="somedata">
    <span> {{somedata}} </span>
 </ng-template>
```

 

Selection_273

**Comment by elliotwesoff** [comment]
I get the same error as @daniloff200 . This feature would be extremely helpful if it worked! I don't want to create components for every template that needs to take advantage of input parameters. Is there any chance this could be fixed?

**Comment by julianseeger** [comment]
Nope sorry. IIRC it worked for me perfectly 3 years ago but when I checked the code today, I even had problems following the control flow to that line.  
It looks like the context doesn't even reach that point now.
The Project where this issue came up is moving to a simpler approach for modals meanwhile and it doesn't look like I'll spend enough time on this problem to fix it. So I'm really sorry but if nobody else fixes this, feel free to close this PR.  
If it wasn't important enough for the last 3 years it probably isn't now.

**Comment by elliotwesoff** [comment]
@julianseeger the HEAD on that file shows that the context and initialState variables should be available in the scope of that function, but which is the right one to use? I don't mind fixing it myself and creating a PR, but following the control flow is quite difficult and I can't figure out how to debug it locally. @daniloff200 help!

**Comment by daniloff200** [comment]
Well, I've tried to use these changes again, but still, got the same error.
Not sure, is it a correct way to fix that, or not

**Comment by elliotwesoff** [comment]
@daniloff200 well that's a bummer. Thanks for your help anyway!

**Pull request closed without merging**
