### PR TITLE
feat (datepicker) - Set startingDay of the week via bs-config

### LINKED ISSUE #2622: Setup startingDay/first day of week to monday
Hello,

I would like to ask how to set first day of the week to Monday. As I read through the library I can see that in the DatepickerConfig there is option to set up startingDay to something else as 0 (which defaults to Sunday).
However setting like:

<input class="form-control" placeholder="Datepicker" bsDatepicker **[startingDay]="1"** **[bsConfig]="options"** [minDate]="minDate" [maxDate]="maxDate" #dp="bsDatepicker">

gets me an error:
Can't bind to 'startingDay' since it isn't a known property of 'input'

and bsConfig has no such property as starting day or something similar.
Changing local does not effect this option. What am I missing ? Big thanks

### PR DESCRIPTION
**Pull request by SidekickJohn**
- [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [x] added/updated demos.

Closes #2622 
@valorkin @IlyaSurmay  please check this and tell me where I can help to finish this.

### CODE REVIEW

**Comment by PerfectlyNormal** [comment]
Nice work!

Would be slightly better if it read the start date from the configured locale. The locales already contain this, as `week.dow` (https://github.com/valor-software/ngx-bootstrap/blob/663f07899113f6b58c5164851fd2d345156ddd06/src/bs-moment/i18n/sv.ts#L58)

**Comment by SidekickJohn** [comment]
@PerfectlyNormal thanks for the hint. <br/>
I got an other suggestion. <br/>
How about making this `week.dow` as default value only if there is no other value provided via bs-config?
That way you could still set a divergent start-day-of-the-week if you need it (which could be the case). <br/>
But before I'm adding this I will wait to see what the gatekeepers think of my existing solution.

**Comment by PerfectlyNormal** [comment]
@sidekickjohn Yes, that is the ideal way. I guess I expressed myself poorly, as that was what I really want.

**Comment by andre-c-andersen** [comment]
This looks good. Looking forward to it. Was about to look for another date picker, but since this looks to be coming in the not to far off future, I'll wait.

**Comment by valorkin** [comment]
hey, I was absolutely sure that this issue is fixed, sorry
before merging this PR I want to fix: getting the first day of a week from locale
then this PR may not be needed

@SidekickJohn thank you so much for the contribution! :)

**Comment by SidekickJohn** [comment]
@valorkin getting the first day of the week from locale would be the best thing to start with, so thank you! But don't you think setting a different start day via bs-config might be useful for some other use cases?

**Comment by valorkin** [comment]
@SidekickJohn it could be, we will see

**Comment by valorkin** [comment]
@SidekickJohn thanks again, please rebase your PR on top of dev
after merge of https://github.com/valor-software/ngx-bootstrap/pull/2970
now it should respect locale! :D

**Comment by andre-c-andersen** [comment]
@SidekickJohn and @valorkin. Configuring it only using the local is indeed a first step, but remember that locale also changes the language of the date elements. This means a US English interface which uses the ISO 8601 date standard (i.e., Monday first) won't be possible. We're working on a Scandinavian webapp, thus language localization isn't important just yet (and might not ever be), but date localization is. Having Sunday as the first day of week is very foreign to our users and will make the app look sloppy. Having Monday as the first day of week and an arbitrary European language for the date element names is even worse.

**Comment by valorkin** [comment]
There are en-gb locale in English and Monday first

**Comment by andre-c-andersen** [comment]
@valorkin Thanks. That could work for us. Doesn't seem like there are any unfortunate language idiosyncrasies showing up either. So, that's good. That said, there are probably plenty of other use cases where a forced first weekday override makes sense.

**Comment by valorkin** [comment]
@SidekickJohn thanks for PR again:)
please check our latest docs structure
ask @EvilAlexei if you will have any questions

**Comment by valorkin** [comment]
with this merged: https://github.com/valor-software/ngx-bootstrap/pull/3271
you will be able to have more granular control over locales

**Comment by valorkin** [comment]
now it's feasible via locale :)

**Comment by wautersj** [comment]
I've read most of the tickets and comments and am not able to change the first day of the week. 

In our application the user can pick it's own day (one of the seven) as his preferred starting day of the week.
And I should configure the datePicker accordingly, of course.

When I look at the BsDatepickerConfig, there seem to be no option to do this. 
But I see people are confirming this is possible (!?)

Can someone explain to me, how to do this?

We're currently running: "ngx-bootstrap": "^5.6.2"



SO much thanks in advance!!

**Pull request closed without merging**
