### PR TITLE
feat(modal): add functionality for identifying which modal triggered the events

### LINKED ISSUE #2917: feat(modal): add functionality for identifying which modal triggered the events
Suppose we have two modals in a component and are subscribed to events available, we are  unable to identify from which modal is triggered.

Plunkr: https://embed.plnkr.co/jas1u9F7DchyBeN33hCw/

### PR DESCRIPTION
**Pull request by meshubh**
Emitting the dialogRef on modals onShown and onHidden events.

This closes #2917

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Review by daniloff200 — APPROVED** [review]

**Comment by daniloff200** [comment]
hey, @meshubh, I see, that Travis build is broken, and it requires some codefixes. Could you please fix it?

**Comment by meshubh** [comment]
Hi,

I'll look into it.

**Comment by swalia20** [comment]
@meshubh , @daniloff200 

Can we emit modalRef or some kind of reference to indicate which modal triggered the event in onShow event also as per requirement in my application. Also is it feasable to selectively not subscribe for these events for a particular BsModalService instance.

**Comment by lexasq** [comment]
Seems irrelevant, you receive modalId now.

**Pull request closed without merging**
