### PR TITLE
fix(chore ci): change sourceRoot to deepen ng cli run scope, add ampe…

### PR DESCRIPTION
**Pull request by belinef**
fix(chore ci): change sourceRoot to deepen ng cli run scope, add ampersands to prevent multiple scopes in script run.

### CODE REVIEW

**Review by IraErshova — DISMISSED** [review]

**Review by daniloff200 — DISMISSED** [review]

**Comment by daniloff200** [comment]
@dmitry-zhemchugov  for unknown reason, both Smoke tests jobs  are failed
could you check that please?

**Comment by IraErshova** [comment]
> @dmitry-zhemchugov for unknown reason, both Smoke tests jobs are failed
> could you check that please?

@belinef thought that it could be because of his changes. Need more investigation

**Review by IraErshova — DISMISSED** [review]
Everything looks good to me, but I have doubts regarding this moment
http://dl3.joxi.net/drive/2020/02/20/0023/0818/1569586/86/a6974f8520.png
@belinef Could you please approve that this code is correct?

**Comment by belinef** [comment]
> Everything looks good to me, but I have doubts regarding this moment
> http://dl3.joxi.net/drive/2020/02/20/0023/0818/1569586/86/a6974f8520.png
> @belinef Could you please approve that this code is correct?

@IraErshova in case for `styles` and `polyfills` there is no restrictions in path. There only restriction in `assets` which path should be started from project `sourceRoot`.

**Review by IraErshova — APPROVED** [review]

**Review by daniloff200 — APPROVED** [review]

**Pull request merged**
