### PR TITLE
feat(datepicker): datepicker and daterangepicker allow to select a day from other months

### LINKED ISSUE #4485: Datepicker: allow selection for days from adjacent months.
### Feature request:
Datepicker doesn't allow selection of days that don't belong to the displayed month.
This behavior is hard-coded [here](https://github.com/valor-software/ngx-bootstrap/blob/b4c0bcb18732713c4732992b6987ed1d11990941/src/datepicker/themes/bs/bs-daterangepicker-container.component.ts#L64) for date range picker and [here](https://github.com/valor-software/ngx-bootstrap/blob/b4c0bcb18732713c4732992b6987ed1d11990941/src/datepicker/themes/bs/bs-datepicker-container.component.ts#L62) for single date picker.

It would be great to have an option in datepicker config to allow this.
Ideally picker would change the current month as well to the one the selected day belongs to.

Styling may still indicate that the day is from another month.

### PR DESCRIPTION
**Pull request by mc-suchecki**
fixes #4485 

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by mc-suchecki** [comment]
@Domainv @valorkin can you give me some feedback on this? I think I should hide this feature behind a flag in Datepicker config, do you agree? Do you have some name suggestions?

I'll add unit tests, docs and examples after the rest of the code is accepted. :)

**Comment by mc-suchecki** [comment]
@Domainv @valorkin can I get some feedback on this?

**Comment by mc-suchecki** [comment]
@Domainv @valorkin could you please take a look at this PR? I would like to know if you are interested in implementing this. If so, please suggest the next steps for me. Should there be a toggle to switch this feature on/off? What should be the default setting?

**Comment by valorkin** [comment]
Thanks for a PR, was fixed in other PR, and already available in v3.1.3
https://valor-software.com/ngx-bootstrap/#/datepicker#select-dates-from-other-month

**Comment by valorkin** [comment]
PR was by @daniloff200 but I don't recall PR number

**Comment by daniloff200** [comment]
That's it :) https://github.com/valor-software/ngx-bootstrap/pull/4828

**Comment by valorkin** [comment]
Thanks

**Pull request closed without merging**
