### PR TITLE
feat(dropdown): rollout completely rewritten bs-dropdown version

### PR DESCRIPTION
**Pull request by valorkin**
should fix all these issues:
https://github.com/valor-software/ng2-bootstrap/labels/comp%28dropdown%29

### CODE REVIEW

**Comment by SergeyKuryatnick** [comment]
Fixed:
https://github.com/valor-software/ng2-bootstrap/issues/1674
https://github.com/valor-software/ng2-bootstrap/issues/1749
https://github.com/valor-software/ng2-bootstrap/issues/1623
https://github.com/valor-software/ng2-bootstrap/issues/1415
https://github.com/valor-software/ng2-bootstrap/issues/802
https://github.com/valor-software/ng2-bootstrap/issues/569
https://github.com/valor-software/ng2-bootstrap/issues/530
https://github.com/valor-software/ng2-bootstrap/issues/6
https://github.com/valor-software/ng2-bootstrap/issues/1540
https://github.com/valor-software/ng2-bootstrap/issues/1217
https://github.com/valor-software/ng2-bootstrap/issues/591
https://github.com/valor-software/ng2-bootstrap/issues/478

Not fixed:
https://github.com/valor-software/ng2-bootstrap/issues/1596 - multi-dropdown is unavailable for now

**Comment by valorkin** [comment]
fixes #1674, fixes #1749, fixes #1623, fixes #1415, fixes #802, fixes #569, fixes #530, fixes #6,
fixes #1540, fixes #1217, fixes #591, fixes #478

feat: you can pass dropdown configuration in `forRoot()` method
feat: now you can add dropdown to body by using `container="body"`

BREAKING CHANGES:
- `DropdownModule` renamed to `BsDropdownModule`, same to all dropdown components added `bs` prefix
- `addToggleClass` option is deprecated, now you need to add `dropdown-toggle` class manually if needed
- `dropdownMenu` menu become a template selector, so `*` should be added
sample:  `<ul dropdownMenu>` should become `<ul *dropdownMenu>`
- `onToggle` event deprecated use `isOpenChange` instead
- `appendToBody` deprecated, use `container="body"` instead, now dropdown behaviour and attachment params alligned with tooltips and popovers
- `keyboardNav` deprecated
- `disabled` renamed to `isDisabled`
- `dropdownToggle` doesn't prevent default behaviour anymore

**Comment by touqeershafi** [comment]
is this available in master?

**Comment by valorkin** [comment]
you mean in npm?

**Comment by touqeershafi** [comment]
Yeah, how can i use this using npm.

I've tried using `npm install ng2-bootstrap@beta --save` but the changes is not effecting.

**Comment by linusbrolin** [comment]
@valorkin why is keyboardNav deprecated?
I can't find any information why this was done...
So keyboard navigation in the dropdown will no longer work after this update?

**Comment by valorkin** [comment]
You use keyboard nav? I will get it back later

**Comment by linusbrolin** [comment]
Ok, good to know.
Yeah, I use keyboard navigation from time to time.

**Comment by valorkin** [comment]
My next prio is finish new datepicker, which is implemented half of a year ago... shame on me

**Comment by valorkin** [comment]
And then Typeahead, where I will need a keyboard navigation... bit this time it will be much smarter

**Comment by umagon** [comment]
I, too, am unable to update ng2-bootstrap. My current version is 1.4.2.

**Comment by rzubov-devpro** [comment]
@valorkin  Looks like you have to bump package version to make it possible to get changes via npm usual way. Till that we have to use     "ng2-bootstrap": "*" in package.json

**Comment by valorkin** [comment]
Bumped :)

**Comment by RakeshMaddala** [comment]
@valorkin - Can you please provide me some information related to keyboardNav ? Is it available now? if not, then is it planned for release ?

**Pull request merged**
