### PR TITLE
fix(timepicker): fix 12hour in 12/24 format

### LINKED ISSUE #5125: Timepicker no accept 12hour in 12/24 format
### Bug description or feature request:

I use the Timepicker to work with 12/24h format. The problem occurs when I typing the hour to 12h. The component convert to zero hour.

### Plunker/StackBlitz that reproduces the issue:
To reproduce this situation: 
1 - Access the demo page https://valor-software.com/ngx-bootstrap/#/timepicker#meridian
2 - Click button "12H / 24H"

3 - In the hour field type 12

4 - Press "TAB"

5 - The value o hour will change to "00"

6 - The correct values should be 12:54

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 4.0.0
Angular: 7.2.9
Bootstrap: 4.3.1

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
- Closes #5125

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Review by RaphaelYan — APPROVED** [review]

**Comment by brboi** [comment]
Hello @FrancescoBorzi !

It seems the checks have failed only for unauthorized access, am I wrong ?

See the bottom of this log: 
https://travis-ci.org/valor-software/ngx-bootstrap/jobs/541279523

**Comment by FrancescoBorzi** [comment]
@biddaputzese I'm not sure about that, I'm not the author of this library ( I just tried to contribute from time to time )

**Comment by brboi** [comment]
Yet it seems that it is definitely this following command which has failed:
`$ npm publish --tag $TRAVIS_COMMIT`

See lines 1948-1949
```
npm ERR! code E401
npm ERR! 401 Unauthorized - PUT https://registry.npmjs.org/ngx-bootstrap-ci - You must be logged in to publish packages.
 ```

**Review by brboi — APPROVED** [review]

**Comment by cedricduffournet** [comment]
Could this be merge in the next version ? This timepicker issue is a bit annoying for 24-hour system

**Comment by FrancescoBorzi** [comment]
@Domainv @ludmilanesvitiy

**Comment by Domainv** [comment]
Sorry, I a bit overloaded, I'll see it on Thursday

**Pull request merged**
