### PR TITLE
feat(datepicker): add Norwegian locale

### PR DESCRIPTION
**Pull request by simjes**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by simjes** [comment]
@valorkin any chance you could take a look at this :)?

**Comment by simjes** [comment]
@IlyaSurmay could you take a look at this?

**Comment by simjes** [comment]
@Domainv could you take a look at this?

**Review by DanielRyan — DISMISSED** [review]
Looks good, the code works

**Comment by DanielRyan** [comment]
I also need this language in the date picker

**Comment by valorkin** [comment]
@Domainv lgtm

**Comment by simjes** [comment]
@valorkin @Domainv Updated

**Comment by ffarkhondeh** [comment]
@valorkin What's the status of this? Seems like it's so close but nothing in the past 16 days.

**Comment by valorkin** [comment]
Sorry, we had couple of issues we had focused on

**Review by Domainv — APPROVED** [review]

**Comment by ludmilanesvitiy** [comment]
Datepicker demo with new locale tested in CHrome, FF - looks good. Tests passed, build success.

**Review by valorkin — APPROVED** [review]

**Pull request merged**
