### PR TITLE
feat(typeahead): add animation

### PR DESCRIPTION
**Pull request by Domainv**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by ludmilanesvitiy** [comment]
Tested in IE, Edge, FF, Chrome. The only thing which needs to take care of is adaptive + animation. Typeahead jumping in this case.
Peek 2019-05-28 15-41

**Comment by Domainv** [comment]
fixed

**Comment by ludmilanesvitiy** [comment]
Smoke tested in IE, Chrome, FF - looks good.

**Pull request merged**
