### PR TITLE
feat(pagination): add custom template functionality

### LINKED ISSUE #2044: feat(pagination): add ability to change the pager template in the pagination component
I'm in the process of migration of an NG1 app to NG2, i was using uiBootstrap pagination with custom template, with ng2 i'm using ngx-bootstrap and i'm missing this such cool feature. would be nice if you guys implement the ability to use custom templates.

### PR DESCRIPTION
**Pull request by IraErshova**
Add custom template functionality

Close #2044

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Review by daniloff200 — DISMISSED** [review]
Don't see something weird or wrong here, but, needs a good testing from @dmitry-zhemchugov  :)

**Review by daniloff200 — DISMISSED** [review]

**Comment by dmitry-zhemchugov** [comment]
Tested. Need fix regarding "..." in the "Centering the active page link" demo
@IraErshova

**Comment by IraErshova** [comment]
@dmitry-zhemchugov I fixed the issue

**Comment by dmitry-zhemchugov** [comment]
Tested. Ready to merge

**Review by daniloff200 — APPROVED** [review]

**Pull request merged**
