### PR TITLE
Add feature in datepicker to select custom dates in footer issue #4588

### PR DESCRIPTION
**Pull request by imranmajeed123**
This PR is for new issue #4588 requesting to add footer with custom dates 

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by imranmajeed123** [comment]
I could not add tests because there are no *spec.ts files related to my changes.

**Comment by imranmajeed123** [comment]
Can Anybody please review this PR?

**Comment by daniloff200** [comment]
hey, @imranmajeed123 , there are a bunch of conflicts here.
Could you please resolve them?

**Comment by daniloff200** [comment]
This PR has a loooot of conflicts, and now, it's really hard to make it work.
Also, we discussed that change with the team, and decided to make this feature not like a footer buttons, but, like [quick ranges](https://valor-software.com/ngx-bootstrap/#/datepicker#quick-select-ranges) that we have in datepicker -> exactly the same buttons, but, for datepicker.

**Pull request closed without merging**
