### PR TITLE
feat(datepicker): prevent overflow if adaptivePosition is set to true

### PR DESCRIPTION
**Pull request by niklaushug**
## Motivation
If the calendar of `[datepicker]` or `[daterangepicker]` is wider than `<input>` and if <input> is positioned on the very left or right of the viewport, it is likely that the calendar is not completely accessible.

## Solution 
By using modifier `preventOverflow` of `PositioningService` in `bs-datepicker-container.component.ts` and `bs-daterangepicker-container.component.ts` an overflow is prevented. I used the same logic like it was used for `popover.directive.ts` and `tooltip.directive.ts`.

## PR Checklist
 - ✓ read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - ✓ built and tested the changes locally. --> Manual test on local server and automatic test by executing `npm run test`.
 - X added/updated tests.
 - ✓ added/updated API documentation --> see bs-datepicker.config.ts
 - X added/updated demos --> A demo for [adaptive-position](http://localhost:4200/ngx-bootstrap/#/components/datepicker?tab=overview#adaptive-position) exist already .

## Related issue
- https://github.com/valor-software/ngx-bootstrap/issues/5705

### CODE REVIEW

**Review by valorkin — APPROVED** [review]
looks great to me. thanks for your help

**Comment by talamaska** [comment]
I think this should be reverted. It is breaking a behavior from v6 and v7, and maybe even earlier. This was working fine. Now if your modal is smaller and the container had overflow auto, the date picker positions on top of the clicked field, totally hiding the text field and creating awkward experience. I don't think the overflow of the container should somehow break the position of the datepicker. It should look only at the position relative to the body, so that it avoids going offscreen, not trying to avoid going of an overflowed container

**Comment by talamaska** [comment]
This is on v 8.0.0
image
image

**Comment by talamaska** [comment]
This is even weirder on v 7.1.2
image
 Here it can go outside of the overflow modal, but tries to alternate bottom position with left and right, while it should alternate only top and bottom. But at least is not positioning itself over the field

**Comment by niklaushug** [comment]
I am sorry that this change has bad implication. Have you checked already the configuration for `allowedPositions`?

Exposing more [PositioningOptions](https://github.com/valor-software/ngx-bootstrap/blob/3e818fdffb77ab3d88e9ea1b27d448bed9437343/src/positioning/models/index.ts#L29) to `BsDatepickerContainerComponent` seems to me a reasonable approach for flexibility. It is the same approach like it is used in [popover.directive.ts](https://github.com/valor-software/ngx-bootstrap/blob/3e818fdffb77ab3d88e9ea1b27d448bed9437343/src/popover/popover.directive.ts#L158) and [tooltip.directive.ts](https://github.com/valor-software/ngx-bootstrap/blob/3e818fdffb77ab3d88e9ea1b27d448bed9437343/src/tooltip/tooltip.directive.ts#L278).

Forcing options `flip` and `preventOverflow` to have the same value seems to me a good choice. May should option `boundariesElement` exposed as well?

Exposing more options is not the real cause. I reason if the problem could be located in `positioning.service.ts`?

**Comment by talamaska** [comment]
Seems like allowedPositions was not documented on the web site for the v 8.
Also it doesn't seem to exist in 7.1.2 where I have things positioned on the side :)

On version 8.0.0 the preventOverflow is enabled if I choose adaptivePosition, which is not what I want. they should be controlled separately. Maybe if I have those exposed and boundariesElement, I might have the desired behavior, because I would be able to use adaptivePositon and set the boundariesElement  to be the window not the scroll element or some other container. In addition the prevent overflow also should be a separate config. The current v8 datePicker doesn't seem to specify a default boundariesElement, I wonder how it is passed and what uses the positioning service.

**Comment by niklaushug** [comment]
If `boundariesElement` is not set the default in [preventOverflow.ts](https://github.com/valor-software/ngx-bootstrap/blob/3e818fdffb77ab3d88e9ea1b27d448bed9437343/src/positioning/modifiers/preventOverflow.ts#L23)  is used.

I am open for decoupling options `flip.enabled` and `preventOverflow.enabled`. Option `adaptivePosition` could still be used as fallback and for compatibility.

Option `adaptivePosition` was introduced by @Domainv . May he wants to share his thoughts?

It would make sense to handle [popover.directive.ts](https://github.com/valor-software/ngx-bootstrap/blob/3e818fdffb77ab3d88e9ea1b27d448bed9437343/src/popover/popover.directive.ts#L158) and [tooltip.directive.ts](https://github.com/valor-software/ngx-bootstrap/blob/3e818fdffb77ab3d88e9ea1b27d448bed9437343/src/tooltip/tooltip.directive.ts#L278) the same way.

**Comment by talamaska** [comment]
> If boundariesElement is not set the default in [preventOverflow.ts](https://github.com/valor-software/ngx-bootstrap/blob/3e818fdffb77ab3d88e9ea1b27d448bed9437343/src/positioning/modifiers/preventOverflow.ts#L23) is used.

Maybe That's the issue with the date picker then.

Wondering why do you invent your logic for positioning and not using the Angular CDK overlay and portal stuff?

**Comment by valorkin** [comment]
> > If boundariesElement is not set the default in [preventOverflow.ts](https://github.com/valor-software/ngx-bootstrap/blob/3e818fdffb77ab3d88e9ea1b27d448bed9437343/src/positioning/modifiers/preventOverflow.ts#L23) is used.
> 
> Maybe That's the issue with the date picker then.
> 
> Wondering why do you invent your logic for positioning and not using the Angular CDK overlay and portal stuff?
> 

Oh, that's an easy question, our positioning is oldef than cdk

**Comment by talamaska** [comment]
Ok, so should I expect a change that will help me resolve my issues with the datepicker positioning.

**Comment by valorkin** [comment]
for v8 started a serious of refactoring activities, what kind of change you would love to see?

**Comment by talamaska** [comment]
at least the exposing of those props we discussed above -  boundariesElement and make preventOverflow configurable, by default it could be linked with the adaptivePosition, but I need to specify the boundaries element of the datepicker, to avoid limiting it's position to a scroll element, I would rather limit it in a window.

**Comment by valorkin** [comment]
let us take a look

**Comment by talamaska** [comment]
While looking into this, is there a way to have an adaptive position of the dropdown? I know about the dropup prop, but i think I can't set it just before the dropdown opens.

**Comment by talamaska** [comment]
@valorkin @niklaushug Is there an issue in order to track the progress? It is really important for me to know the progress and the roadmap for 8.x

**Pull request merged**
