### PR TITLE
perf(datepicker): Fix Datepicker Memory Leaks

### PR DESCRIPTION
**Pull request by Gbuomprisco**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

To reproduce:
- go to Datepicker page and take and take Memory snapshot with DevTools
- go to another page and back to datepicker page a couple times
- take memory snapshot again and search for DatePicker classes -> see the number go up

Before the fix:
Screenshot 2019-10-21 at 00 00 33

After the fix, numbers appear more normal and memory usage goes back to a consistent 60mb:
Screenshot 2019-10-21 at 20 21 13

### CODE REVIEW

**Comment by daniloff200** [comment]
Wow! 
We definitely gonna look at it with @Domainv  ASAP ! Thanks for your contribution, @Gbuomprisco !

**Review by valorkin — DISMISSED** [review]
looks solid to me! thank you so much

**Comment by aklaffenboeck** [comment]
Are there any news on this topic? We are also heavily affected by this issue.

**Comment by cyptus** [comment]
@daniloff200  could we please get this merged?

**Review by daniloff200 — APPROVED** [review]

**Pull request merged**
