### PR TITLE
feat(build): update to Angular 9.1.0

### LINKED ISSUE #5744: Angular 9 Support
This feature request is not any kind of new idea, just an official request to support Angular 9.

On to the issue template!

**Is your feature request related to a problem? Please describe.**

My team would like to upgrade, but first we need our dependencies to support it. This library is the last one.

**Describe the solution you'd like**

I would like ngx-bootstrap to officially support Angular 9.

**Describe alternatives you've considered**

At this point I think we just wait. Eventually I suppose we'd have to consider migrating to another library that stays up to date ... but let's not get ahead of ourselves. :)

**Additional context**

I think we've more than covered it!

### PR DESCRIPTION
**Pull request by daniloff200**
closes https://github.com/valor-software/ngx-bootstrap/issues/5744

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by dmitry-zhemchugov** [comment]
I have tested this PR, works as expected and looks well.

**Comment by daniloff200** [comment]
well, right now we just need a review from @valorkin :)

**Comment by castevinz** [comment]
Hi,
Wha's the news about this PR ? 
I'm waiting for this kind of merge to be able to use it with my angular 9 app. I still have datepicker locale problems since upgrade from angular 7 => 9, even if I update imports like "ngx-bootstrap/datepicker" (related to https://github.com/valor-software/ngx-bootstrap/issues/5653)...
Thx for updates ;)

**Comment by castevinz** [comment]
What about this angular 9 branch? I can't wait to use it!

**Comment by samshay** [comment]
Do you have a date of availability of this PR ?
I need it to switch all my apps to angular 9.

Thanks.

**Comment by daniloff200** [comment]
@samshay you can use current bootstrap version, if you use Angular 9.
Right now we support version 9, but, without migrating to it

**Comment by valorkin** [comment]
dropping support of view engine is discouraged for libraries, read more here:
https://v9.angular.io/guide/ivy#maintaining-library-compatibility

**Comment by daniloff200** [comment]
@valorkin  the initial idea of adding ngcc in postinstall script was one of the issues during the build, which appeared after migration to Angular 9.1.0.

Right now I'm trying to reproduce it again without ngcc, and can't do it, so, probably we won't need that line and everything should be ok with compatibility

**Review by valorkin — APPROVED** [review]

**Pull request merged**
