### PR TITLE
Corrected all Grammatical errors in the Readme file!

### PR DESCRIPTION
**Pull request by sakkshm**
solved issue #5438

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by daniloff200** [comment]
Fix conflicts, please

**Comment by daniloff200** [comment]
hey, @sakkshm , can you resolve conflicts?

**Comment by sakkshm** [comment]
I'll try to 
Please give me 2 days

**Comment by daniloff200** [comment]
@sakkshm any updates? 14 days passed... :(

**Comment by sakkshm** [comment]
I'll not be able to do it sorry.

**Pull request closed without merging**
