### PR TITLE
feat(dropdown): add arrow key navigation for dropdown list

### LINKED ISSUE #4015: refactor(dropdown): add key navigation to dropdown component
Add an option to switch between items in dropdown's list using keyboard buttons: `arrow up` and `arrow down`

### PR DESCRIPTION
**Pull request by 5earle**
Closes #4015 & #5555 

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by 5earle** [comment]
Addresses #4015

**Comment by adrienverge** [comment]
Thanks @5earle, getting back keyboard support would be great!
@valorkin what do you think of this PR?

**Comment by daniloff200** [comment]
Almost 2 years passed, but,  better late, then never.

I've tested this functionality, looks like, works well

**Review by daniloff200 — DISMISSED** [review]

**Review by valorkin — DISMISSED** [review]
Should be good enough, keyCode is MDN deprecated, so could be issues in FF.
https://caniuse.com/#search=keyCode
but seem good for now

**Comment by dmitry-zhemchugov** [comment]
Tested. There are a lot of issues regarding non-standard demos like "Manual triggering", "Trigger by isOpen property", "Nested dropdowns (experimental)" and others. This feature should be fully reworked.

**Comment by daniloff200** [comment]
well, let's try to rework it, because, there's already 2 issues / requests about this feature

**Review by daniloff200 — DISMISSED** [review]

**Review by daniloff200 — APPROVED** [review]

**Review by valorkin — APPROVED** [review]
lgtm, not sure about initial focus for dropdown-menu, but let's try :)

**Pull request merged**
