### PR TITLE
refactor: Capitalize pt-br's locale month names

### PR DESCRIPTION
**Pull request by sougiovn**

### CODE REVIEW

**Comment by valorkin** [comment]
@gigioSouza please revert change to package-lock

**Comment by sougiovn** [comment]
@valorkin `package-lock.json` reverted

**Review by valorkin — APPROVED** [review]

**Comment by valorkin** [comment]
@gigioSouza thanks for PR!

**Comment by rafaelss95** [comment]
@valorkin All i18n files declare month names lowercased, why only this was changed?

**Comment by valorkin** [comment]
Not all, there are similar PR in momentjs

**Comment by valorkin** [comment]
PS is there are any i18n best practice for month names?

**Comment by rafaelss95** [comment]
> PS is there are any i18n best practice for month names?

I don't know one, however [Angular (<sub>more specifically CLDR</sub>) uses a lowercased version.](https://github.com/angular/angular/blob/ce40e85cbbf100df3e5507d26e961582ffdd1a17/packages/common/locales/pt.ts)

**Pull request merged**
