### PR TITLE
fix(datepicker): select correct month and year from month picker view…

### LINKED ISSUE #4500: Month selector selects wrong year when months from multiple years are displayed
When in month selection view with displayMonths > 1, no matter which year calendar we choose the month from, always the year displayed in first calendar is selected.

### Issue reproduction
Choose any datepicker or daterangepicker with displayMonths > 1 (say, 2). Go to year selection and choose 2018. Since displayMonths is 2, month selection for both 2018 and 2019 will be displayed. Choose July from 2019 calendar. July 2018 gets selected.

### PR DESCRIPTION
**Pull request by johnsmathew**
… when displayMonths > 1

Fixes #4500

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by valorkin** [comment]
@johnsmathew hey, thans for PR! Could you please add a test case for this issue?

**Comment by johnsmathew** [comment]
@valorkin  Added test case for this scenario. I couldn't find any spec files for datepicker. So created a new spec file.

**Comment by johnsmathew** [comment]
@valorkin Can this be reviewed and merged please.

**Comment by ludmilanesvitiy** [comment]
Tested in Chrome, FF - latest, looks good. Need to update test for not disabling ts-lint rules and ready for merge.

**Review by Domainv — APPROVED** [review]

**Review by valorkin — APPROVED** [review]

**Pull request merged**
