### PR TITLE
feat(datepicker): allow disabling year selection

### PR DESCRIPTION
**Pull request by sucotronic**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [?] added/updated tests.
 - [x] added/updated API documentation.
 - [?] added/updated demos.

### CODE REVIEW

**Comment by daniloff200** [comment]
hey, @sucotronic !
If there an issue, which this PR fixes, or, it's just your enhancement proposal?

**Comment by sucotronic** [comment]
Hi Dimitri. It's my proposal for a setting to disable year selection through a config setting.

**Comment by daniloff200** [comment]
hey, @sucotronic , I've updated your branch with some small changes, also, added demo for it.
I've also changed the config property to _disableYears_

Looks like something wrong with this logic, because, I still have ability to select other year, even with disableYears as true. Maybe, I misunderstood your idea, or, did something wrong?
Could you check this, please?

**Comment by daniloff200** [comment]
Looks like this one was abandoned.
In case anyone wants to work on that, or, @sucotronic you will back, ping me here, and I will reopen that

**Pull request closed without merging**
