### PR TITLE
feat(modal): add method to change modal window class

### PR DESCRIPTION
**Pull request by ghost**
Was added:
- demo `Change class`
- functionality for changing modal's window class after the modal window was opened

joxi_screenshot_1542299975482

Related to #2824

### CODE REVIEW

**Review by Domainv — DISMISSED** [review]

**Comment by Domainv** [comment]
needs add tests

**Comment by ludmilanesvitiy** [comment]
screenshot from 2018-12-06 12-31-44
This is a view from FF 63.0.3
Need to fix button view for FF (should be centered or aligned to width as in Chrome)

**Comment by ghost** [comment]
can't reproduce 
joxi_screenshot_1544112709783

**Comment by ludmilanesvitiy** [comment]
Retested with different FF versions and diff OS, looks good.

**Review by valorkin — APPROVED** [review]

**Pull request merged**
