### PR TITLE
Feat time picker display utc

### LINKED ISSUE #5635: Add UTC timezone support to timepicker
**Is your feature request related to a problem? Please describe.**

When building apps that work across timezones, it is frequently necessary to show/capture dates and times in a different timezone that the user's local one.

`BsDatepickerConfig` now has a `useUtc` property for showing/capturing UTC dates/date ranges, but timepicker does not have the same support.

**Describe the solution you'd like**

Add support for an equivalent `useUtc` property to `Timepicker` / `TimepickerConfig`.

**Describe alternatives you've considered**

Somebody already did all the work to add full timezone support to timepicker in this PR:

https://github.com/valor-software/ngx-bootstrap/pull/4747

But nobody could be bothered to review it, so the author closed it. Maybe it could be resurrected?

### PR DESCRIPTION
**Pull request by juicyarts**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

closes #5635

### CODE REVIEW

**Comment by daniloff200** [comment]
hey @juicyarts !
Good to see u again! Looks like, you've managed to move your work to a new PR
I assume, it's related to  https://github.com/valor-software/ngx-bootstrap/issues/4731, right?

**Comment by juicyarts** [comment]
Hey @daniloff200 , this one is related to  #5635 , there's another one in my fork that handles offset  / #4731 here: https://github.com/juicyarts/ngx-bootstrap/pull/1. It made more sense to align the interface with the datepicker for the offsetTarget and use `useUtc` for consistency, and these two properties (useUtc, offset) can live and work by themselves

**Comment by juicyarts** [comment]
@daniloff200 i have a hard time running the whole unit test suite.. see the logs in the observations below. 
The failing e2e tests don't seem to be related to my changes, could this be related to cypress flakiness? 


<details>
<summary>Some observations/issues i documented while working on the pr</summary>

 ### test runner inconsistencies
When running `npx nx run timepicker:test` locally these tests are run:

```
 PASS   timepicker  src/timepicker/testing/timepicker-controls.util.spec.ts
 PASS   timepicker  src/timepicker/testing/timepicker.component.spec.ts (7.005 s)
```

When running in ci pipeline:

```shell
PASS timepicker src/timepicker/testing/timepicker.component.spec.ts (11.499 s)
PASS timepicker src/timepicker/testing/timepicker-controls.util.spec.ts
FAIL timepicker src/timepicker/testing/timepicker.utils.spec.ts
```

somehow locally the filter is missing the `timepicker.utils.spec file`.

EDIT: my bad, seems like the timepicker.utils.spec are all disabled using `xdescribe` and the comment `OMG` :D

### Datepicker test suites have issues that cause the runner to be stuck

This behaviour can be reproduces in the `development` branch, so does not seem to be related to my chnages.

```shell
 PASS   datepicker  src/datepicker/testing/bs-datepicker-navigation-view.spec.ts
(node:59007) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Zone'
    |     property '_zoneDelegate' -> object with constructor 'ZoneDelegate'
    --- property 'zone' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (internal/child_process/serialization.js:117:20)
    at process.target._send (internal/child_process.js:805:17)
    at process.target.send (internal/child_process.js:703:19)
    at reportSuccess (/Users/yildiz/repos/huess/lib/ngx-bootstrap-ja/node_modules/jest-worker/build/workers/processChild.js:67:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59007) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:59007) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:59009) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Zone'
    |     property '_zoneDelegate' -> object with constructor 'ZoneDelegate'
    --- property 'zone' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (internal/child_process/serialization.js:117:20)
    at process.target._send (internal/child_process.js:805:17)
    at process.target.send (internal/child_process.js:703:19)
    at reportSuccess (/Users/yildiz/repos/huess/lib/ngx-bootstrap-ja/node_modules/jest-worker/build/workers/processChild.js:67:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59009) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:59009) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Unhandled Promise rejection: Failed to load timepicker.component.html ; Zone: ProxyZone ; Task: Promise.then ; Value: Failed to load timepicker.component.html undefined".

      at console.error (../../node_modules/@jest/console/build/BufferedConsole.js:161:10)
      at Object.api.onUnhandledError (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1104:29)
      at handleUnhandledRejection (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1132:17)
      at _loop_2 (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1123:21)
      at Object.api.microtaskDrainDone (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1127:17)
      at drainMicroTaskQueue (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:629:22)
      at ZoneTask.Object.<anonymous>.ZoneTask.invokeTask [as invoke] (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:522:25)
      at invokeTask (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1658:18)
      at XMLHttpRequest.globalZoneAwareCallback (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1684:21)
      at XMLHttpRequest.callTheUserObjectsOperation (../../node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
```

</details>

**Comment by juicyarts** [comment]
This one https://github.com/juicyarts/ngx-bootstrap/pull/1 builds and tests without any issues.. Since its base is this branch i guess the e2e tests in the last run of this branch were just flaky..

**Comment by juicyarts** [comment]
So is there something missing or do you want me to change something? Do i need to assign someone here? How can we ensure this PR does not end up like the last one..? :) @daniloff200

**Comment by daniloff200** [comment]
Well, looks good to me, @juicyarts 
Gonna check that tomorrow, how it works

**Review by daniloff200 — DISMISSED** [review]

**Comment by valorkin** [comment]
@juicyarts hello, thank you so much for your work and help
please convert `useUTC` from input to configuration option
and I will be glad to merge it

**Comment by juicyarts** [comment]
Hey @valorkin, i changed it but am not too sure if this was what you requested. Have a look and let me know if somethings missing. https://github.com/juicyarts/ngx-bootstrap/pull/1 is waiting for this one to be merged, i would adopt the approach of only exposing these options in the config too if thats how you want it.

**Comment by juicyarts** [comment]
Hey guys. Don't want to be annoying.. Is there something i can still do here to ? @valorkin & @daniloff200  ?

**Review by lexasq — APPROVED** [review]

**Comment by daniloff200** [comment]
Holly molly!

frankenstein-its-alive

**Comment by lexasq** [comment]
@daniloff200 we're back to our opensource roots)

**Pull request closed without merging**
