### PR TITLE
fix(doc): fix of file name mistake

### LINKED ISSUE #5456: wrong file name
### Bug description or feature request:
wrong file name `doc/spec/tooltip/tooltip.examles.placement.use-case.md`

need to change it to `tooltip.examples.placement.use-case.md`

is it possible to add `hacktoberfest` label to it?

### PR DESCRIPTION
**Pull request by sameshl**
correct name of file
from tooltip.examles.placement.use-case.md -> tooltip.examples.placement.use-case.md

closes #5456

### CODE REVIEW

**Review by daniloff200 — CHANGES_REQUESTED** [review]
tooltip.**examlpes**.placement.use-case.md

:thinking:

**Comment by sameshl** [comment]
@daniloff200 My bad :sweat_smile:. Made the correction

**Review by daniloff200 — APPROVED** [review]

**Review by Domainv — APPROVED** [review]

**Comment by daniloff200** [comment]
hi @sameshl   !
Thanks again for the PR!
Could you please fill out this [form](https://docs.google.com/forms/d/1tHjwGbh8CIrLcOjcMOHoY7xiLNXpQWNXySwhJbwNrH8/edit) so we can send some swag to you? Thanks!

**Comment by sameshl** [comment]
Thanks @daniloff200 Will do!

**Pull request merged**
