### PR TITLE
Use isObservable from rxjs to check if typeahead property is in fact an Observable

### PR DESCRIPTION
**Pull request by fizdalf**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [X] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [X] built and tested the changes locally.
 - [ ] added/updated tests. _I couldn't find a good way of testing for this, as I couldn't find a good reason behind the issue that motivated me to push this PR, but I think it still good practice to let the RXJS library tell you if something is an Observable or not, instead of trying to find ways of checking ourselves._
 - [ ] added/updated API documentation. _There's no changes in API documentation._
 - [ ] added/updated demos. _There's no changes in the demos._

### CODE REVIEW

**Comment by valorkin** [comment]
hey, looks good, but please revert changes to package-lock.json

**Comment by fizdalf** [comment]
I have reverted the package-lock.json file. Hope it's all good now 😃

**Review by valorkin — APPROVED** [review]
LGTM

**Comment by ludmilanesvitiy** [comment]
Typeahead smoke tested, looks good. RFM

**Review by valorkin — APPROVED** [review]
Thanks for PR!

**Pull request merged**
