### PR TITLE
feat(typeahead): add feature to do multiple search w/ specified delimiter

### LINKED ISSUE #5781: feat(typeahead) Allow to be able to search multiple times in the same input
**Is your feature request related to a problem? Please describe.**

I need to be able to have typeahead suggestion for multiple possible values in the same input field. When I type a sentence for example and, after using specific character it should start giving matches and then again and again.

**Describe the solution you'd like**

Being able to enter multiple values and after using a specified delimiter to start a new search again but concatenate a picked value. For example there are **Apple** and **Mango** in typeahead values, when I search "**App**" it will suggest **Apple**, I press enter and it populates the input. Then if I type one of provided delimiters, like comma or space etc., and after that type "**M**" the dropdown should give **Mango** as an option to pick. When I take it, press enter, the input should have **Apple,Mango** (when comma used as separator) or **Apple Mango** (when space used). Possible delimiters could be provided as a separate option. It should also allow to type something else in between which doesn't match any values like **Apple,something,Mango**
This link demonstrates almost exactly what I am requesting just comma doesn't need to be automatically inserted and other than comma kind of delimiter can be provided.
[http://jsfiddle.net/Sherbrow/BwDmM/300/](http://jsfiddle.net/Sherbrow/BwDmM/300/)

**Describe alternatives you've considered**

Considered my own implementation or helping to make a contribution for this feature in this project.

**Additional context**

### PR DESCRIPTION
**Pull request by lehetap**
feature allows to show typeahead dropdown even after any value
already entered by typing one of provided delimiters to be able to pick
again; keeps all searched values, described in #5781

Closes #5781

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by lehetap** [comment]
@valorkin @daniloff200 Please review this feature as soon as possible. I added demo, tests, all that required. I **desperately** need it in my project.

**Comment by daniloff200** [comment]
hey, @lehetap 
Thank you for your contribution!
I was a little bit busy with some other fix requests, also, there were bunch of issues, related to 6.0.0 . I will check this PR during this week

**Comment by daniloff200** [comment]
Well, I've checked that feature, looks really awesome!
Also, looks like all other things works exactly in the same way, and nothing was broken, so,  gonna merge that
It will be available in 6.0.1 release

Gonna check units and e2e's and, if everything works well, merge that

**Review by daniloff200 — APPROVED** [review]

**Comment by pavloldev6** [comment]
Thank you! I'm glad all worked out well!

**Comment by lehetap** [comment]
Thank you! I'm glad everything worked out well!

**Pull request merged**
