### PR TITLE
fix(modal-service): Fix modal service not dismissing during animation

### LINKED ISSUE #3711: Modal created via ModalService is not hidden after calling .hide()
### Bug description or feature request:
Calling the hide() function on a modal will not hide it if it's not shown fully. This means that if I open a dialog to signal a usually long loading server call which finishes too fast (faster than the modal animation) the hide() will be called but has no effect. You can see this in my demo with three manual delays. At no or small delays the dialog just stays open, at 150ms it isn't even shown properly and at 250ms it works as expected. Another interesting behaviour is that opening many dialogs and closing them fast will leave the GUI unclickable (E.g. in my demo by clicking and holding ctrl+2).

### Plunker/StackBlitz that reproduces the issue:
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-ftrzc4?file=app%2Fapp.component.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.2

Angular: 4.4.6

Bootstrap: 3.3.7

### PR DESCRIPTION
**Pull request by cmckni3**
Fixes #3711

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by cmckni3** [comment]
Not sure if I need to update tests or not.

**Comment by cmckni3** [comment]
Any update on this?

**Comment by Domainv** [comment]
Will take a look as soon as possible

**Comment by cmckni3** [comment]
any update?

**Review by daniloff200 — APPROVED** [review]

**Comment by dmitry-zhemchugov** [comment]
I have tested this PR, everything works as expected, ready to merge.

**Comment by yuri-apanasik** [comment]
@daniloff200 @dmitry-zhemchugov this delay on modal close is really annoying now... and there is no 'legal' way to remove this delay. Please, make it possible to override this behavior, at least with injecting my our TRANSITION_DURATIONS values

**Pull request merged**
