### PR TITLE
feat(Modal): available to use 'BsModalRef.setClass' in modal component ngOnInit lifecycle

### LINKED ISSUE #5320: feat(Modal): available to use 'BsModalRef.setClass' in modal component ngOnInit lifecycle.
### 🐛Bug description or feature request:
Feature Request 😆

### Explanation
Now, we have to use 'setClass' method like this. 
```
this.bsModalService.show(CartSuccessModalCompoennt, {
 'class': 'cart-modal'
});
```
or we can use this way.
```
const bsModalRef = this.bsModalService.show(CartSuccessModalCompoennt);
bsModalRef.setClass('cart-modal');
```

In this way, we have to call 'bsModalRef.setClass' or set options {'class': 'cart-modal'} in everywhere we call .show method.

I suggest 🙋‍♂️ that we should make bsModalRef.setClass method available to call in modal component lifecycle. 

This is the example what i suggest.
```typescript
@Component({
  selector: 'cart-success-modal',
  templateUrl: './cart-success-modal.component.html',
  styleUrls: ['./cart-success-modal.component.scss']
})
export class CartSuccessModalComponent {
  constructor(public bsModalRef: BsModalRef) {
  }

  ngOnInit() {
    this.bsModalRef.setClass('modal-sm');
  }
}
```
In 5.1.1 version, above example not works because at that moment (ngOnInit timing), this.bsModalRef.setClass is just Function (native code). 

So, i change bsModalService._showModal implementation to assign setClass function before starting ngOnInit lifecycle. 

I make PR request for this feature. Please see the changes and give me a feedback.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.1.1 

Angular: 7.x, 8.x

Bootstrap: 3.x

### PR DESCRIPTION
**Pull request by leo6104**
Please see this issue 🙏 
closes https://github.com/valor-software/ngx-bootstrap/issues/5320

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by leo6104** [comment]
Conflicts resolved.

**Review by valorkin — DISMISSED** [review]
thanks for contribution! looks good to me

**Comment by leo6104** [comment]
In our company projects, i applied custom bsModalService through extending class & overriding method to prove PR works. 
It was no problem with 50k users within 7 months. I think it is enough time to prove it works. 

```
@Injectable()
export class MapiaBsModalService extends BsModalService {
  constructor(rendererFactory: RendererFactory2, clf: ComponentLoaderFactory) {
    super(rendererFactory, clf);
  }

  // tslint:disable-next-line:no-any
  _showModal(content: any): BsModalRef {
    const modalLoader = (this as any).loaders[(this as any).loaders.length - 1];
    const bsModalRef = new BsModalRef();
    const modalContainerRef = modalLoader
      .provide({ provide: ModalOptions, useValue: this.config })
      .provide({ provide: BsModalRef, useValue: bsModalRef })
      .attach(ModalContainerComponent)
      .to('body');

    bsModalRef.hide = () => {
      modalContainerRef.instance.hide();
    };
    bsModalRef.setClass = (newClass: string) => {
      modalContainerRef.instance.config.class = newClass;
    };

    // call 'show' method after assign setClass, content in bsModalRef.
    // it makes modal component's bsModalRef available to call setClass method
    modalContainerRef.show({
      content, isAnimated: this.config.animated, initialState: this.config.initialState, bsModalService: this
    });
    modalContainerRef.instance.level = this.getModalsCount();

    bsModalRef.content = modalLoader.getInnerComponent() || null;

    return bsModalRef;
  }
}
```

If you have a problem with merge this PR, please leave your opinion.

**Review by daniloff200 — DISMISSED** [review]

**Review by daniloff200 — APPROVED** [review]

**Comment by dmitry-zhemchugov** [comment]
via Hubstaff
User: Dmitry Zhemchugov

Project: int_ngx-bootstrap (OSS) - https://app.hubstaff.com/projects/304822
Date Range: 01/20/20 - 01/21/20
Work session total: 3:26:31
Billable: Yes

Grand total: 3:26:31

**Pull request merged**
