### PR TITLE
feat(datepicker): add Vietnam (vi) locale to date picker

### PR DESCRIPTION
**Pull request by nartc**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Review by nhutlbuit — DISMISSED** [review]

**Comment by vtnhut94** [comment]
Add vn locale

**Comment by kuribohzz98** [comment]
Add vi locale 👍

**Comment by hieu-ht** [comment]
+1

**Review by envil — COMMENTED** [review]
Correct translations

**Review by tnanhpt — COMMENTED** [review]
good

**Comment by tiennampham23** [comment]
Helpful (y)

**Comment by vuonghv** [comment]
Very helpful. Thanks

**Comment by tiendo93** [comment]
Thank you!!!

**Review by Domainv — APPROVED** [review]

**Comment by ludmilanesvitiy** [comment]
Datepicker tested, looks good.

**Comment by quannv1198** [comment]
good

**Pull request merged**
