### PR TITLE
feat(tooltip): add delay to config

### LINKED ISSUE #4029: TooltipConfig to add delay option
Currently TooltipConfig only support 3 options but not delay. We looking at adding delay to TooltipConfig at global level.

Thanks!

### PR DESCRIPTION
**Pull request by fynnfeldpausch**
The default delay of tooltips can be configured.

closes #4029

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by valorkin** [comment]
you have a delay to config, but it will be used by an tooltip component?

**Comment by fynnfeldpausch** [comment]
@valorkin Not sure what your question is. The default config will be used by the tooltip directive, yes. As the directive uses an input with the same name, the default config writes to that value in the constructor. The default config can be provided.

**Review by valorkin — DISMISSED** [review]
Looks good! Thanks for your help!

**Comment by ludmilanesvitiy** [comment]
@fynnfeldpausch @valorkin WE've added new property to config, bit didn't describe this property in Demo documentation http://localhost:4200/#/tooltip#tooltip-config
But at all tested, looks good.

**Review by Domainv — APPROVED** [review]

**Comment by valorkin** [comment]
thanks for your time and help!

**Pull request merged**
