### PR TITLE
feat(chore): updated angular up to angular 15

### PR DESCRIPTION
**Pull request by SvetlanaMuravlova**
feat(chore): updated angular up to angular 15

### CODE REVIEW

**Review by valorkin — APPROVED** [review]

**Comment by Alexveselun** [comment]
The version is not displayed on the header menu(perhaps it is displayed like this only in the preview and on the DEV env, it will be fine) Just to double-check
Screenshot from 2022-12-12 13-03-54
Screenshot from 2022-12-12 13-04-46

**Comment by Alexveselun** [comment]
On the "Discover" page the logo is not displayed 
1. Open the "Home" page
2. Click on the "Discover" link on the left-side menu
Screenshot from 2022-12-12 13-08-57

**Comment by Alexveselun** [comment]
From my side, except for this [issue](https://github.com/valor-software/ngx-bootstrap/pull/6531#issuecomment-1346308051), no critical issues were found. I want to separately conduct regression testing for the entire application on the dev env.

**Comment by SvetlanaMuravlova** [comment]
> The version is not displayed on the header menu(perhaps it is displayed like this only in the preview and on the DEV env, it will be fine) Just to double-check Screenshot from 2022-12-12 13-03-54 Screenshot from 2022-12-12 13-04-46

it will be fixed after deploy, cause we don't have vesions list on preview channels, it is only on github pages

**Review by Alexveselun — APPROVED** [review]

**Pull request merged**
