### PR TITLE
bsConfig range fix

### PR DESCRIPTION
**Pull request by GabriFedi**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by GabriFedi** [comment]
fixed date range picker input that got empty after have filled the input manually.

**Comment by daniloff200** [comment]
Works and loooks good to me!

**Review by daniloff200 — APPROVED** [review]

**Comment by daniloff200** [comment]
hey @GabriFedi !
Thanks again for your help !  Could you please fill out this [form](https://docs.google.com/forms/d/1tHjwGbh8CIrLcOjcMOHoY7xiLNXpQWNXySwhJbwNrH8/edit) so we can send some swag to you? Thanks!

**Comment by GabriFedi** [comment]
> hey @GabriFedi !
> Thanks again for your help ! Could you please fill out this [form](https://docs.google.com/forms/d/1tHjwGbh8CIrLcOjcMOHoY7xiLNXpQWNXySwhJbwNrH8/edit) so we can send some swag to you? Thanks!

I submitted the form. Thank you :)

**Review by valorkin — APPROVED** [review]

**Comment by valorkin** [comment]
thank you!

**Pull request merged**
