### PR TITLE
comp(sortable) improvements

### PR DESCRIPTION
**Pull request by Le0Michine**
touch support
directives (allows to make such things as tables or other complicated templates sortable)
limitations for transferring items between containers can be set
bux fixes (e.g. selected item wasn't unselected if was dropped outside container)

### CODE REVIEW

**Comment by Le0Michine** [comment]
could affect #1554

**Comment by Le0Michine** [comment]
@valorkin hey, it was created more when 3 weeks ago :)

**Comment by valorkin** [comment]
I am here, horey

**Comment by doug62** [comment]
When will this be merged?

**Comment by DanniB** [comment]
Is it possible to limit the array size? I would like to assign a number of m tones to n modi, where m>n.

**Pull request closed without merging**
