### PR TITLE
feat(modal): modal show return id and bsModalRef contain id

### LINKED ISSUE #2917: feat(modal): add functionality for identifying which modal triggered the events
Suppose we have two modals in a component and are subscribed to events available, we are  unable to identify from which modal is triggered.

Plunkr: https://embed.plnkr.co/jas1u9F7DchyBeN33hCw/

### PR DESCRIPTION
**Pull request by dkosasih**
Modal is not emitting id upon shown and hidden event. So we know which modal we can to react on upon shown or hidden.
`modalService.hide(<id>)` to close by id or `modalService.hide()` to hide all modal

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated demos.

resolve #2917

### CODE REVIEW

**Comment by racedale** [comment]
Yes! I need this so I can prevent test automation from breaking when moving to bootstrap modals.

**Comment by valorkin** [comment]
Hey, first of all, thanks for PR!
I agree that we need a way to close specific modal via service
should be 3 ways:
- when we get modal ref and this ref should have `.hide` method, to close specific modal
- via global modal service `.hide` without params - and hide all modals
- with modal ref param or Parial modal ref with id, to close specific modal

**Comment by dkosasih** [comment]
greetings @valorkin !
let me try to understand the ways of closing the modal you mentioned:
> when we get modal ref and this ref should have .hide method, to close specific modal

This is how it's working right now `this.bsModalRef.hide()`. correct?

>via global modal service .hide without params - and hide all modals

This would introduce breaking changes because calling hide() from service required `level` parameter - implemented this by replacing level to id and remove the specified id if passed otherwise remove all layer. I will update the pull request after I tidy up the code.

> with modal ref param or Parial modal ref with id, to close specific modal

not sure if I understand this one, because modal ref is tied to 1 modal instance, but calling `modalref.hide()` is already cloding that specific modal.

**Comment by dkosasih** [comment]
`modalService.hide(<id>)` to close by id 
`modalService.hide()` to close all modals.

**Comment by daniloff200** [comment]
hey, @dkosasih , I see some conflicts here.
Could you please resolve them?

**Comment by daniloff200** [comment]
hey!
I see, that you fixed conflicts, but, build is broken, even on the 1st step. Does this code work well on your local machine?

**Comment by dkosasih** [comment]
I was pushing the code without building it locally. I am giving it another try and will make sure it build locally before pushing again.
Apologies.

**Comment by dkosasih** [comment]
Hi @daniloff200,
The branch has been resolved, built, and tested.

Please have a look. Thanks.

**Comment by daniloff200** [comment]
@dkosasih  I've checked, it works correct, but, I see one test failure.
I'm gonna try to dive into it, to understand, what went wrong, but, in case you have time, you also can try to check it

**Review by daniloff200 — DISMISSED** [review]

**Comment by dkosasih** [comment]
> @dkosasih I've checked, it works correct, but, I see one test failure.
@daniloff200 I had a look at the failing tests, they are all `Carousel Multilist`. 
image

**Comment by daniloff200** [comment]
Nope, that's not the failed test.
There some errors from the demo angular app, but, it's not related 

I was talking about `HeadlessChrome 83.0.4103 (Linux 0.0.0) Service: BsModal showModal should add providers to modal injector FAILED`

Check https://travis-ci.org/github/valor-software/ngx-bootstrap/jobs/711832094 this job from travis, and you will see what I mean

That test is in `bs-modal.service.spec.ts`

**Comment by dkosasih** [comment]
I can see the problem now. However, I couldn't get it to run test locally. I kept getting ivy ngcc error. Have this happened to you before?
image

It fail randomly, not only with tab, sometime mini-ngrx... random.

**Comment by daniloff200** [comment]
I used to see such errors before, during migration to Angular newest versions. Try to remove **dist** & **node_modules** folder, and then, reinstall them and re-run the build @dkosasih

**Comment by dkosasih** [comment]
@daniloff200 So the test that's failed is bs-modal.spec.ts:75. It was failing because in bs-modal.service.ts:162, modalContainerRef.instance.config.id does not get service mocked properly. 
I am unable to mock the injected config into the service, so I use `modalContainerRef.instance.config?.id` instead. 
It may not be ideal, but I am not sure how I can mock object with property. 

I upgrade @type/jasmine to 3.1.0, but many tests start to fail.

**Comment by daniloff200** [comment]
@dkosasih  thanks for your work!
I'm gonna update PR with latest development, double check, that everything still works correct, and, merge that.
We merged a lof of stuff this week, especially for modals, so, I think it's fine for now

**Review by daniloff200 — APPROVED** [review]

**Pull request merged**
