### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by amalsebs**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by daniloff200** [comment]
hello, @amalsebs !
Can you please describe, what's the purpose / advantage of this change? I can't see any actual difference

**Comment by amalsebs** [comment]
Sir it's a minor change but it will improve the accuracy in the
responsiveness of the page

**Comment by EvilAlexei** [comment]
@amalsebs could you provide additional info about the difference in `1` and `1.0` in this case?
In my opinion, there is no difference.

**Comment by daniloff200** [comment]
@amalsebs  any updates?

**Pull request closed without merging**
