### PR TITLE
Chore : Upgrade Angular 18

### PR DESCRIPTION
**Pull request by MatthiasHuygelen**
# Issues
#6652 

# Description
updated @nx/* and @angular/* family to version 18

updated via migrations

regenerated package-lock.json

updated README.md, mentioning that next major version will require/support Angular 18

fixed eslint issues

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [x] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Review by pregress — APPROVED** [review]

**Review by PTAHume — APPROVED** [review]
Looks good

**Comment by MatthiasHuygelen** [comment]
@valorkin can you assign a reviewer please

**Review by ailasa — APPROVED** [review]

**Review by valorkin — APPROVED** [review]

**Comment by jonthe101** [comment]
How about merging this? Would like to get an angular 18 compatible version of ngx-bootstrap :)

**Comment by MatthiasHuygelen** [comment]
> How about merging this? Would like to get an angular 18 compatible version of ngx-bootstrap :)

i'm not authorized to merge

**Comment by valorkin** [comment]
LGTM

**Comment by lukaVarga** [comment]
@valorkin can you also release the new version on npm? 🙏

**Comment by MilesHeise** [comment]
is there a time frame on when this fix is likely to get published?

**Comment by Guling85** [comment]
HI i cant get version 13.0 from npm. Is there anything wrong?

**Comment by MatthiasHuygelen** [comment]
> HI i cant get version 13.0 from npm. Is there anything wrong?

hasn't been released yet

**Comment by Guling85** [comment]
> > HI i cant get version 13.0 from npm. Is there anything wrong?
> 
> hasn't been released yet

Oh! crap I though it was released because under README Compatibility list it says version 13.x. 
I need to downgrade my project :). Is there any ETA? for this Thanks

**Comment by msitruk** [comment]
waiting for npm release thx for your work !

**Comment by skatterwe** [comment]
Anything that can be done to prepare/help with releasing?

**Comment by kees-wiegel-visma** [comment]
> > > HI i cant get version 13.0 from npm. Is there anything wrong?
> > 
> > 
> > hasn't been released yet
> 
> Oh! crap I though it was released because under README Compatibility list it says version 13.x. I need to downgrade my project :). Is there any ETA? for this Thanks

Same here! Let us know if we can help in any way :)

**Comment by tasdpp** [comment]
New to "open source". Is this the norm for the speed of how things move through the process for what looks to be a very popular piece of code with over 286K downloads a week?

**Comment by slubowsky** [comment]
ping @valorkin

**Comment by hamirilb** [comment]
Looks like version 13 is not published on npm.

**Comment by skatterwe** [comment]
no, unfortunately its not published yet. i've asked @valorkin on linked in too if there is something to help with. unfortunately no answer yet

**Comment by toanho-dev** [comment]
it s published as version 18.0.0
https://www.npmjs.com/package/ngx-bootstrap/v/18.0.0

**Pull request merged**
