### PR TITLE
fix(typeahead): fix performance issue

### PR DESCRIPTION
**Pull request by Domainv**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by nielswitte** [comment]
@Domainv this adjustment results in `ERROR in (1,1): Directive TypeaheadContainerComponent, Property 'hidden' does not exist on type 'TypeaheadContainerComponent'.` when building with tsconfig.json:

```
"angularCompilerOptions": {
        "fullTemplateTypeCheck": true
}
```

It seems to use 'hidden' as a variable instead as a string. You should probably add `visiblity: hidden` to the `style` attribute 2 lines lower.

**Comment by daniloff200** [comment]
hi @nielswitte 
could you provide more info about that, or, some stackblitz demo?

I suppose, you're talking about adding `visibility:hidden` here :

```   style: 'position: absolute;display: block;visibility: hidden' ``` , right?

**Comment by nielswitte** [comment]
@daniloff200 
Yes that is exactly what i ment. 

For an example, if you download this simple project: https://angular-pfgfpv.stackblitz.io
install the npm packages and add/update the tsconfig.json file with this:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```


then when running production build: `ng build --prod`
it will output:

```
ng build --prod

chunk {0} runtime.a8ef3a8272419c2e2c66.js (runtime) 1.45 kB [entry] [rendered]
chunk {1} main.5b86fa47a477a9ac91c1.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.58610b9bc4daa2c4d34a.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} polyfills-es5.715e2b4ad3f2e067c4ca.js (polyfills-es5) 79.6 kB [initial] [rendered]
chunk {4} styles.6cb061d4d269276b945c.css (styles) 0 bytes [initial] [rendered]
Date: 2020-01-23T12:06:28.556Z - Hash: 09863311a725feca6d6d - Time: 12360ms

ERROR in (1,1): Directive TypeaheadContainerComponent, Property 'hidden' does not exist on type 'TypeaheadContainerComponent'.
```

If this doesn't work, the only steps required is that you have a module which imports the typeahead module from ngx-bootstrap 5.4+ and the angular settings in tsconfig.json.

**Comment by juliocardosoventura** [comment]
It doesn't work for me!

ng build --prod

chunk {0} runtime.a8ef3a8272419c2e2c66.js (runtime) 1.45 kB [entry] [rendered]
chunk {1} main.5b86fa47a477a9ac91c1.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.58610b9bc4daa2c4d34a.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} polyfills-es5.715e2b4ad3f2e067c4ca.js (polyfills-es5) 79.6 kB [initial] [rendered]
chunk {4} styles.629ea5b8bfea077ffe10.css (styles) 545 kB [initial] [rendered]
chunk {scripts} scripts.9b1207587ef3aa866146.js (scripts) 14.1 kB [entry] [rendered]
Date: 2020-01-23T13:09:14.552Z - Hash: 691a55dce0378972c1e3 - Time: 33363ms

ERROR in (1,1): Directive TypeaheadContainerComponent, Property 'hidden' does not exist on type 'TypeaheadContainerComponent'.

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "@fortawesome/*": ["src/assets/@fortawesome/*"]
    },
    "resolveJsonModule": true
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

    "ngx-bootstrap": "^5.4.0",
    "@angular/core": "~8.2.14",


5.4.0 to 5.5.0 fixed.

**Comment by daniloff200** [comment]
Yeah, I also see that, but, I think, the main reason for it is https://github.com/valor-software/ngx-bootstrap/pull/5589/files#diff-d68518de260a5f25cc59995692262a40L31

Issue with `` and '' 
Gonna try to fix it right now, and check, if everything works great, hope, we will create a 5.4.1. with a fix

**Comment by daniloff200** [comment]
@juliocardosoventura  @nielswitte 
hey!
thanks again for reporting that, we're planning to release 5.5.0. beta version tomorrow, so, you will be able to check , was it fixed or not

**Comment by juliocardosoventura** [comment]
@daniloff200 
Hello, I look forward to the change.
Have a nice day!

**Comment by daniloff200** [comment]
ngx-bootstrap 5.5.0 is now available 
cc @juliocardosoventura  @nielswitte

**Comment by nielswitte** [comment]
@daniloff200 thank you

**Comment by daniloff200** [comment]
@nielswitte  please , drop a message, was this issue fixed, or not, for you, with the new release, or we need some more work for it
Thanks!

**Comment by juliocardosoventura** [comment]
Well done, from 5.4.0 to 5.5.0 fixed.
Thanks!

**Comment by daniloff200** [comment]
giphy

**Pull request merged**
