### PR TITLE
feat(datepicker): allow marking dates as disabled

### PR DESCRIPTION
**Pull request by gkaran**
Added ability to disable any date from the datepicker using a callback function `(date: Date) => boolean`. This is something we have been missing in the new version but had in older ones.

Although this PR might look similar to #4491 it is actually not, since with a callback we are able to have much more control on which dates should be disabled. Take for example that you have a ticker booking system and you want to disable the dates for which no tickets are available.

Unit tests have not been added/updated since it wasn't actually clear where to place them for datepicker. Please let me know where I can add some and I will.

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [X] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [X] built and tested the changes locally.
 - [ ] added/updated tests.
 - [X] added/updated API documentation.
 - [X] added/updated demos.

### CODE REVIEW

**Comment by csegyud** [comment]
Just kindly inquire if this PR is still under consideration or has been abandoned? I really need this functionality and it is amazing that you (@gkaran) already started working on it. Could I somehow help you? Sorry, I'm new to this codecov stuff. 

Will this feature work on Angular 4.2.5 (ngx-bootstrap 2.0.2, Bootstrap 3.3.7)? 
Thx.

**Comment by gkaran** [comment]
As far as I know, the only problem right now is that this PR will decrease the test coverage but I couldn't find any tests that I could enhance/add for datepicker.

As for the version you mention I don't know if they are going to port this fix in versions <3.x, probably someone from the maintainers should answer. I think that probably you can achieve the same in your version using the datepciker component and not the directive. Will get back to you on that tomorrow.

**Comment by csegyud** [comment]
Thank you @gkaran. In my opinion, it is a very useful feature and the old date picker had a similar feature - so I think it has a good chance that they will port it there too. Should I ask it somewhere else or they read this here too?

BTW, if they would not, I could do a dirty patch on my current version based on your work, after moving it outside of node_modules. Or is it a nasty idea?

**Comment by gkaran** [comment]
@csegyud you would have to build the project then and include it in your project (whatever this means).

Regarding the setup you have now, in a project of mine (which currently trying to upgrade to Angular 6 but am blocked by this feature) I use Angular 4.4.6 and ngx-bootstrap 2.0.5. With this setup and the `datepicker` component I am able to disable specific dates by passing to the `dateDisabled` input an array or object following this format: `{date, mode: 'day'}` where `date` is a `Date` object. Hope this will help you (at least for now).

**Comment by csegyud** [comment]
Thank you George, sounds like a good idea. Will come back to you next week - now I have to leave for a trip abroad. Best.

**Comment by csegyud** [comment]
@gkaran, I managed to implement this functionality with the old date picker, based on your explanation. Thank you very much for your help. Note: It works with Angular 4.2.5 too.

**Comment by ludmilanesvitiy** [comment]
This feature is already implemented and presented on our demo site:
https://valor-software.com/ngx-bootstrap/#/datepicker#days-disabled
https://valor-software.com/ngx-bootstrap/#/datepicker#dates-disabled
Peek 2019-04-17 11-02

**Pull request closed without merging**
