### PR TITLE
Update carousel.examples.basic.use-case.md

### PR DESCRIPTION
**Pull request by NeelPrime**
Spelling and grammar corrections.
# PR Checklist
Before creating new PR, please take a look at the checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Review by daniloff200 — APPROVED** [review]

**Comment by daniloff200** [comment]
Please,  resolve conflicts

**Review by daniloff200 — CHANGES_REQUESTED** [review]
need to fix merge conflicts

**Comment by daniloff200** [comment]
conflicts fixed

**Review by daniloff200 — APPROVED** [review]

**Review by Domainv — APPROVED** [review]

**Comment by daniloff200** [comment]
Form with swag was sent in #5459

**Pull request merged**
