### PR TITLE
fix(accordion): fix infinite change detection loop in IE11

### LINKED ISSUE #5660: Accordion with animation enabled triggers infinite ChangeDetection Cycles on IE11
Angular: 8.2.14
ngx-bootstrap: 5.5.0
build system: angular cli

Demo Project: https://stackblitz.com/edit/angular-r5bngk
App URL: https://angular-r5bngk.stackblitz.io

I've set up the demo app to log every change detection cycle to the console. If you open the app in chrome and click on the first accordion header it will fire at least twice and then stop. In IE11 it will be run infinitely, causing the app to slow down to a crawl.
This problem only occurs if the [isAnimated] property of the accordion is set to true.

### PR DESCRIPTION
**Pull request by sonicpro**
resolves #5660 

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by IraErshova** [comment]
@dmitry-zhemchugov Need your help with e2e

**Comment by IraErshova** [comment]
Accordion functionality is broken. Needs fix

**Comment by daniloff200** [comment]
IE11 support is over for Angular, so, maybe we should close that.

**Comment by daniloff200** [comment]
Right now it works well, but, can't really check that on IE - stackblitz link from original issue can't even load on IE11 correctly.
The whole accordion functionality works well on other browsers, but, I can't even open app with the docs on IE11, and get some console errors.

IE support for Angular already ended, also, a bunch of the apps gonna also stop IE11 support next year, so, maybe we should close that.

**Pull request closed without merging**
