### PR TITLE
fix(positioning): fix frozen page

### PR DESCRIPTION
**Pull request by Domainv**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by ludmilanesvitiy** [comment]
Smoke tested, in Chrome and FF - looks good.

**Review by ludmilanesvitiy — APPROVED** [review]

**Comment by hisham** [comment]
fyi - I'm still getting frozen pages with 4.1.1. Reverting to 3.2.0 resolves it.

**Comment by ludmilanesvitiy** [comment]
@hisham Hi! Could you, pls specify steps for reproducing frozen page?

**Comment by hisham** [comment]
I don't have exact repro steps unfortunately. It just freezes my app as soon as I go over a tooltip. This issue happened since you refactored the positioning service but I didn't have exact repro steps so didn't log a bug. Was then happy you found it yourself and made a fix but looks like the issue is still there for certain cases atleast.

**Comment by JelleVisser** [comment]
We encountered this same issue. We could eventually reproduce it by having the plugin "LastPass" or "Grammarly" installed in Chrome. We went back to 3.2.0 and that seems to fix it for us.

**Comment by niteshpurohit** [comment]
4.1.1 and on Chrome (Version 73.0.3683.103 (Official Build) (64-bit)) Grammarly installed. in Dev it works fine, prod (default config) and with aot it is freezing. 
Then uninstalled Grammarly from chrome, site starts working.

**Pull request merged**
