### PR TITLE
fix(timepicker): enable_disable timepicker in reactive forms

### LINKED ISSUE #4055: Enabling/disabling a Timepicker control is broken
### Bug description or feature request:

- create a Reactive Form with a Timepicker as Control
- try to enable/disable the control
- the Timepicker will be stuck in disabled mode

### Plunker/StackBlitz that reproduces the issue:

This example is quite self-explanatory:

https://plnkr.co/edit/wcfrep5CFaYnxrb7PtRR?p=preview

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.3

Angular:  5.2.9

Bootstrap: 3.3.7

### Build system:

Angular CLI: 1.7.3
Node: 8.9.1
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

angular/cli: 1.7.3
angular-devkit/build-optimizer: 0.3.2
angular-devkit/core: 0.3.2
angular-devkit/schematics: 0.3.2
ngtools/json-schema: 1.2.0
ngtools/webpack: 1.10.2
schematics/angular: 0.3.2
schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [  ] added/updated tests.
 - [ ] added/updated API documentation.
 - [x] added/updated demos.

This PR fixes: https://github.com/valor-software/ngx-bootstrap/issues/4055

### CODE REVIEW

**Review by valorkin — DISMISSED** [review]

**Comment by ludmilanesvitiy** [comment]
screenshot from 2018-12-17 12-34-24
@FrancescoBorzi @valorkin @Domainv Please, need fix prod build

**Comment by FrancescoBorzi** [comment]
@ludmilanesvitiy @valorkin thanks for checking my PR, however this is a bit old (opened 4 months ago) and it possibly needs to be merged with master first.

About the pipeline failure, I'm currently on holiday with limited access so I cannot fix it now.

**Comment by ludmilanesvitiy** [comment]
I've updated this PR, but issue with prod build should be fixed before testing.

**Comment by FrancescoBorzi** [comment]
@ludmilanesvitiy @valorkin @Domainv 

I've fixed the issue with the build. Now the build is still failing but I think it might not be related to my changes. Can you please have a look?

**Comment by ludmilanesvitiy** [comment]
Tested in Chrome, FF - latest, timepicker looks good.

**Review by valorkin — APPROVED** [review]
Thanks

**Comment by FrancescoBorzi** [comment]
was this included in `3.1.4` or will be part of `3.1.5` ?

**Comment by valorkin** [comment]
Hey, yes. I have merged it just after 3.1.4 release commit )

**Comment by FrancescoBorzi** [comment]
ok then the milestone should be changed

**Pull request merged**
