### PR TITLE
feat(modal): modal service v2 wip

### LINKED ISSUE #2330: feat(modal): pass custom data to the hide() method in Modal
Could you please explain how to pass custom data to the hide() method
`this.dynamicModal.hide(data);`

### LINKED ISSUE #2356: fix(modal): modal does not properly work in a lazy loaded module
To have working modal in a lazy-loaded module you have to import modal module with `forRoot()` in that lazy module which is not correct as `BsModalService` will get a new instance and will not know anything about other modals of other modules (e.g. nesting won't properly work). If you skip the `forRoot()` you will get:

```
ERROR Error: No component factory found for MyModalInLazyLoadedModule. 
Did you add it to @NgModule.entryComponents?
```

That's happening because [ComponentLoaderFactory](https://github.com/valor-software/ngx-bootstrap/blob/development/src/modal/modal.module.ts#L17) is provided only in root module which does not know anything about lazy-loaded injector and factories.

Proper fix would be to have some kind of [overlay service](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/modal/modal.ts#L47)  that is provided with every [ModalModule import](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/modal/modal.module.ts#L15).

Reproduction - https://stackblitz.com/edit/ngx-bootstrap-playground-mtwpzg

### LINKED ISSUE #2917: feat(modal): add functionality for identifying which modal triggered the events
Suppose we have two modals in a component and are subscribed to events available, we are  unable to identify from which modal is triggered.

Plunkr: https://embed.plnkr.co/jas1u9F7DchyBeN33hCw/

### PR DESCRIPTION
**Pull request by IlyaSurmay**
Closes #2917
Closes #2330
Fixes #2356 
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by vincentjames501** [comment]
This seems like a great approach. Any update on this?

**Comment by vincentjames501** [comment]
@valorkin , this would be the great fix!

**Comment by gufigueiredo** [comment]
Any progress on this? This is a high-value improvement!

**Comment by valorkin** [comment]
this approach is definitely better than existing one
but has the same issue with lazy loaded modules

**Comment by daniloff200** [comment]
Totally outdated

**Pull request closed without merging**
