### PR TITLE
enhance position calc to consider boundariesElement input in preventOverflow modifier other then the default 'scrollParent'

### PR DESCRIPTION
**Pull request by Gidi1980**
introduce boundariesElement member in Data interface
consider boundariesElement passed to getBouneries API in preventOverflow
modifier

### CODE REVIEW

**Comment by Gidi1980** [comment]
@valorkin Hi!
Hope you are doing well.

MY above PR did not trigger the travis CI build - am I missing something?
also - could you please kindly review it so if passes it may be merged?

Have a good one!

Gidi

**Comment by valorkin** [comment]
Hi, no idea. Even our push to dev branch not always triggering builds. Time to move on GitHub actions :(

**Comment by Gidi1980** [comment]
> Hi, no idea. Even our push to dev branch not always triggering builds. Time to move on GitHub actions :(

Ok, thanks for the prompt reply! :)

Can you please review or let me know what should be done for this PR to be reviewed / merged?

**Comment by daniloff200** [comment]
ah, I got him triggered with the merge with dev branch :)

**Comment by Gidi1980** [comment]
@daniloff200 @valorkin 
Thanks for triggering the Travis CI.
Glad it passed :)

Can you kindly review / approve / merge this PR ?

Any feedback is appreciated.

**Comment by Gidi1980** [comment]
@valorkin @daniloff200  - Hi guys, hope you are having a great holiday and keeping safe.

Please review / approve this PR when you have a moment so I can go ahead and merge the code.

Have a good one and a happy new year :)

Gidi.

**Review by daniloff200 — APPROVED** [review]

**Comment by daniloff200** [comment]
Looks good for me. I don't think it can break something and somewhere, because, it's some addition to existed functionality, so, we can go ahead with this 

Thanks for your contribution, @Gidi1980 ! :heart:  Wish you all the best in 2021 ! Happy New Year :christmas_tree:

**Comment by Gidi1980** [comment]
Thank you very much @daniloff200 for your time and patience in merging this PR.

Have a good one too! :D

**Pull request merged**
