### PR TITLE
fix for issue 6596

### PR DESCRIPTION
**Pull request by MPruntel**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Review by swapnil0545 — APPROVED** [review]

**Comment by swapnil0545** [comment]
@valorkin  @SvetlanaMuravlova Request you to take a look at this.

**Review by orlandoburli — APPROVED** [review]

**Review by valorkin — DISMISSED** [review]

**Comment by valorkin** [comment]
looks good to me, I will publish when CI is done, thanks

**Comment by MPruntel** [comment]
@valorkin Do you know why CI failed?

**Comment by valorkin** [comment]
just FYI es2022 changes default settings for useDefineForClassFields

**Review by valorkin — APPROVED** [review]

**Pull request merged**
