### PR TITLE
feat(typeahead): focus first

### LINKED ISSUE #1281: fix(typeahead): it is not possible to NOT select any option using keys for submit
Typeahead works fine. I type and get completion suggestions - but it seems to be impossible to NOT select any.

For example:
I type "lorem ip" in a search-input field and get a suggestion for "lorem ipsum".
I am not able to just submit "lorem ip". There is always a preselected option,
that gets submitted on enter.

### LINKED ISSUE #3261: feat(typeahead): Add option not to select first when using typeahead component
### feature request:

I could use a input in typeahead to disable autoselecting the first element from options

Something like @Input() typeaheadAutoSelectFirst = true so that it wouldn't break any existing implementations

### PR DESCRIPTION
**Pull request by joeoh1359**
-Added options to allow User to define Select, Escape, and to ignore keys
--Can override defaults

-Implemented typescriptFocusFirst

closes #3261 
closes #1281

### CODE REVIEW

**Comment by valorkin** [comment]
@joeoh1359 I can understand why you need focus first
but why ignore keys?
if you can split focus first proposal in separate I would love to merge it

**Review by ViktorPlohl — APPROVED** [review]

**Comment by pouellet** [comment]
Hi there, would creating a separate PR for the `typeaheadFocusFirst` part help in getting that feature merged? I don't want to steal any credit from @joeoh1359 contribution, but I'm eager to see this option being added and would be happy to split that part in a separate PR if there's a chance of getting it in faster.

**Comment by pouellet** [comment]
@valorkin, @IlyaSurmay - any chance of merging the typeaheadFocusFirst part if I create another PR for just that part?

**Comment by Rajanusa** [comment]
Hi,
Can any one explain how to implement not to select first by default.
I found someone suggested to override select event.
please suggest how to avoid selecting the first when user is not selecting that.

**Comment by Rajanusa** [comment]
Hi,

Can any one explain how to implement not to select first by default.
I found someone suggested to override select event.
please suggest how to avoid selecting the first when user is not selecting that.

**Comment by Rajanusa** [comment]
Can any one explain how to implement not to select first by default.
I found someone suggested to override select event.
please suggest how to avoid selecting the first when user is not selecting that.

**Comment by Rajanusa** [comment]
> -Added options to allow User to define Select, Escape, and to ignore keys
> --Can override defaults
> 
> -Implemented typescriptFocusFirst
> 
> closes #3261
> closes #1281

Hi

Can any one explain how to implement not to select first by default.
What to do in override Select event

**Comment by ludmilanesvitiy** [comment]
Feature about selecting the first item in typeahead is already implemented and presented on the demo page:
https://valor-software.com/ngx-bootstrap/#/typeahead#first-item-active
https://valor-software.com/ngx-bootstrap/#/typeahead#selected-first-item
Peek 2019-04-15 10-51

**Pull request closed without merging**
