### PR TITLE
feat(chore): updates for angular 14

### PR DESCRIPTION
**Pull request by SvetlanaMuravlova**
Updates for angular 14

### CODE REVIEW

**Comment by DerekLiang** [comment]
It seems that the accordion is broken after Angular 14 upgrade when `isAnimated` flag set to `true`. It can no longer expand after expands all tabs. I am using the link above https://ngx-bootstrap-demo--pr6477-updates-for-angular-0ogih11c.web.app/

Animation

**Comment by dionatan-g** [comment]
Please, we need this PR merged asap

**Comment by valorkin** [comment]
testing, planning to release before monday

**Comment by valorkin** [comment]
e2e works fine on local machine, I will release RC version and then will fix e2e at CI

**Comment by valorkin** [comment]
9.0.0-RC.1 is on npm ;)

**Comment by valorkin** [comment]
9.0.0-RC.2 with proper peer deps and e2e ci passing is on npm
if you find anything - write here, so I could fix fast
on my apps haven't found anything new
planning to release on friday as latest if all good

**Pull request merged**
