### PR TITLE
feat(docs): show code of examples with many components and services

### PR DESCRIPTION
**Pull request by jcjc712**
To show the code of examples which work with many components and services you only need to send an array through "modules" input in "ng-sample-box" component.

### CODE REVIEW

**Comment by jcjc712** [comment]
## To show the code of examples with many components we could do something like...
`serviceEvents: [
    {
      component: require('!!raw-loader?lang=typescript!./service-events/service-events.ts'),
      html: require('!!raw-loader?lang=markup!./service-events/service-events.html')
    },
    {
      component: require('!!raw-loader?lang=typescript!./service-events/service-events.ts'),
      html: require('!!raw-loader?lang=markup!./service-events/service-events.html')
    }
  ]`
**Before**
`<ng-sample-box [ts]="demos.serviceEvents.component" [html]="demos.serviceEvents.html">
  <demo-modal-service-events></demo-modal-service-events>
</ng-sample-box>`
**After**
`<ng-sample-box [modules]="demos.serviceEvents">
  <demo-modal-service-events></demo-modal-service-events>
</ng-sample-box>`

**Comment by valorkin** [comment]
Just to mention, you can see wip PR with huge docs refactoring, this PR will be merged just after it.

Thanks for contribution! :)

**Comment by valorkin** [comment]
@jcjc712 hey, please rebase on latest dev and check how now we are producing docs pages

**Comment by jcjc712** [comment]
@valorkin  Done, Thanks for the notice.

**Comment by valorkin** [comment]
FYI here is how we generate docs now
using config of outlets, aka CMS
https://github.com/valor-software/ngx-bootstrap/blob/4e3e456251c64e0d279b731807667de66496a097/demo/src/app/components/+accordion/accordion-section.list.ts

and this one is responsible for showing multi samples
https://github.com/valor-software/ngx-bootstrap/blob/4e3e456251c64e0d279b731807667de66496a097/demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts

**Comment by Domainv** [comment]
closes as outdated

**Pull request closed without merging**
