### PR TITLE
fix(datepicker): apply date format appropriately

### LINKED ISSUE #3553: data-picker problem:The first default time format error
The first time is

image

But after I chose the time, it is：

image

My configuration is 

```typescript
this.bsConfig = Object.assign({}, { locale: 'zh-cn', rangeInputFormat: 'YYYY/MM/DD' });
```

### PR DESCRIPTION
**Pull request by kimamula**
Fixes #3553 by applying the date format whenever the new date format is set.

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by fabio-percivaldi** [comment]
Hi guys, do you have any news on when will be closed this fix?

**Comment by hajdun** [comment]
Temporary workaround: set form data and use a placeholder formatted date string (two steps).

**Review by Vimallakzz — DISMISSED** [review]

**Comment by daniloff200** [comment]
hey, @kimamula 
Thanks for your contribution! I see some conflicts here, could you resolve them, please?

**Comment by kimamula** [comment]
@daniloff200 done.

**Review by daniloff200 — APPROVED** [review]

**Pull request merged**
