### PR TITLE
fix(dropdown) fixing performance by removing @Hostlistnere('document:…

### LINKED ISSUE #2172: fix(dropdown): performance problems with multiple dropdowns
**Description**

We see a big performance problem when using a high number of Dropdowns (e.g. a list of 100 or more elements, each with his own action dropdown). Especially in dev mode the app is getting unresponsible to clicks for seconds.

**Workaround**

Render the dropdown element on mouseenter (simple *ngIf).

**Notes**
Because of the workaround, I think the problem is the high number of global listeners (for closing the dropdown with an outside click). The guys from ng-bootstrap had an similar problem and solved it by register the listeners only when opening a dropdown and remove them on closing.
See https://github.com/ng-bootstrap/ng-bootstrap/issues/900 for the issue or https://github.com/thbt/ng-bootstrap/commit/65778f33871f838341845d7e30d09a43f218ba13 for the fix.

### PR DESCRIPTION
**Pull request by warash**
Closes #2172

@HostListener('document:click')  is causing huge performance issue. especially if there are many dropdown instances on page. Every instance is assigning global listener to click. Every listnere is causing appRef.tick being triggered. if you have 10 dropdowns on page and you click wherever on page 10 appRef.tick with full changedetection of all elements will be triggered.

### CODE REVIEW

**Comment by Domainv** [comment]
@warash Thank you for the PR.
Now a little loaded will review it as soon as possible

**Comment by ludmilanesvitiy** [comment]
Screenshot from 2019-03-26 15-11-07  ^^^current performance
Screenshot from 2019-03-26 15-06-10  
^^^performance with applying 4605 PR
Screenshot from 2019-03-26 15-05-51 - ^^^performance without any fixes
Also need to pay attention to runOutsideAngular function, which could time to time broke auto-waiting for dropdown open/close inside protractor tests, if they will exist in the app.

**Comment by dklmuc** [comment]
imho there won't be any big performance improvements because of https://github.com/valor-software/ngx-bootstrap/pull/5099/files#diff-d74026377f7ce8e580379903df8e14beR78

**Comment by warash** [comment]
hi @ludmilanesvitiy  i like also 4605 i would be super happy if either 4605 or mine pr would be merged into release.. it has big performance impact even bigger than on presented by you demo pages. becasue in real case scenario changedetection is much longer than on demo page that has no other components instead just dropdowns.. on our page we have pretty haevy kendo grid component which is changedetected multiple of times when clicked. Thanks for making this performance tests.

If it comes to runoutside angular and protractor problem i think it wont be a problem casue i am returing to angular zone by this.ngZone.run() when dropdown is realy opened and we need to inform angular about change.

**Comment by ludmilanesvitiy** [comment]
@warash @dklmuc No worries, guys! This change request is under control and should be in the nearest version bump. I'll let you know!

**Comment by Domainv** [comment]
Closes to prefer #4605

**Pull request closed without merging**
