### PR TITLE
feat(datepicker)  add custom today class for current date via config

### PR DESCRIPTION
**Pull request by ypetrych**

### CODE REVIEW

**Review by SergDi — DISMISSED** [review]

**Comment by fralewsmi** [comment]
Is this related to / resolving https://github.com/valor-software/ngx-bootstrap/issues/3192 ?

**Comment by mccool** [comment]
@Domainv Are there any updates on getting a class added to the current day in the calendar so we can style it ourselves?

**Review by Vonahz — DISMISSED** [review]

**Review by Domainv — DISMISSED** [review]

**Comment by ludmilanesvitiy** [comment]
@Domainv What about adding isToday as a param to config and about the demos for it?

**Comment by ludmilanesvitiy** [comment]
Retested in CHrome and FF - looks good. Today with custom class is available in html.

**Review by valorkin — APPROVED** [review]

**Pull request merged**
