### PR TITLE
feat(datepicker): add catalan lang

### LINKED ISSUE #4959: Add language translation for Catalan
Hello, I would like to add Catalan translations.

I have a local branch with translations and all related tests to this.
I just need to make a pull request but I need permission to set remote branch.

Thank you in advance.

### PR DESCRIPTION
**Pull request by arbatxavier**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.
closes #4959

### CODE REVIEW

**Comment by daniloff200** [comment]
closes #4959

**Review by valorkin — APPROVED** [review]
Looks great to me! Thanks for PR:)

**Comment by ludmilanesvitiy** [comment]
Datepicker Locales demo tested, looks good.

**Review by valorkin — APPROVED** [review]

**Comment by valorkin** [comment]
Thanks for your time and help!

**Pull request merged**
