### PR TITLE
feat(datepicker): add Latvian locale (#hacktoberfest)

### PR DESCRIPTION
**Pull request by MatissJanis**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by daniloff200** [comment]
hey @MatissJanis ! 
Thanks for your contribution! 
Can you please check both https://github.com/valor-software/ngx-bootstrap/pull/5387 or https://github.com/valor-software/ngx-bootstrap/pull/4812 or https://github.com/valor-software/ngx-bootstrap/pull/4634/files as examples of good localization? 
There's not only one file, you have to add this files as an import in different places

Also, add tests for it will be very good!

**Review by daniloff200 — CHANGES_REQUESTED** [review]
need to add locale as an import / export, and add tests

**Comment by MatissJanis** [comment]
Thanks @daniloff200 ! Added tests, exposed import/export  and fixed some bugs in the process 🙂 

Let me know if anything else is wrong/missing.

**Comment by daniloff200** [comment]
Thanks for the fixes @MatissJanis !  Well, I think, that's pretty enough.
@Domainv  thoughts? Can we merge it for next release ?

**Review by daniloff200 — APPROVED** [review]

**Review by Domainv — APPROVED** [review]

**Comment by MatissJanis** [comment]
Thanks guys!

**Comment by daniloff200** [comment]
hey @MatissJanis  !
Thanks again for the PR!
Could you please fill out this [form](https://docs.google.com/forms/d/1tHjwGbh8CIrLcOjcMOHoY7xiLNXpQWNXySwhJbwNrH8/edit) so we can send some swag to you? Thanks!

**Pull request merged**
