### PR TITLE
feat(timepicker):  implements property and logic to control offset in displayed time

### LINKED ISSUE #4731: feat(date/time-picker): add possibility to set offsets
### Bug description or feature request:

I searched for this kind of issues but couldn't find anything that is comparable to our use-case and proposal.

#### use case:
We use the date and time-pickers of ngx-bootstrap in an application that needs to show all date and time values in a specific timezone. Given some companies that a user has access to, the date and time values shown in the application should all refer to the timezone the selected company is operating in no matter where the user/client is located.

I started implementing this in a fork since we definitely need this but if you also see this as a useful feature it would be nice to implement it into ngx-bootstrap.

#### proposal

A new property called `offset` is made available
```typescript
...
@Input() offset: number; // time offset in minutes, can be negative
...
```
```html
<timepicker [(ngModel)]="mytime" [offset]="offset"></timepicker>
<datepicker [(ngModel)]="mytime" [offset]="offset"></datepicker>
```

This adds or subtracts given offset to the "displayed" values and also takes them into account when  working with `min` and `max` properties. The date object itself is not being modified since this is all about the display format. 

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.1.0

Angular: 6.1.6

Bootstrap: 4

### Build system: Angular CLI, System.js, webpack, starter seed:

CLI

### PR DESCRIPTION
**Pull request by juicyarts**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

This implementation is related to https://github.com/valor-software/ngx-bootstrap/issues/4731 .
The purpose is to allow to set offsets for the displayed time in the timepicker.

Here's a use case i want to cover with this:
* a user in Germany is looking at a live representation of a process (some machines doing things) in the United States(Chicago).
* the user in Germany can select a start time to scope the representation of the process
  * the start time shown/selected needs to be in the timezone the process is done in. So the timepicker needs to display UTC-6 although the date object itself does not need to be changed (since its UTC anyway)
  * this is especially important for the usage of min and max values

fixes #4731

### CODE REVIEW

**Comment by juicyarts** [comment]
sorry for toggling this around this much, there are still some things missing:
* [x] extend actions/reducers
* [x] extend functionality of min/max

**Comment by juicyarts** [comment]
I'm not working for the company any more that needed this. Seems like nobody else cared so i'm going to close.

**Comment by daniloff200** [comment]
@juicyarts  I've updated your PR, so sorry about your waiting, and closing this PR
hope, I can resurrect it

**Comment by juicyarts** [comment]
it's been a while.., i'll have a look this weekend if thats not to late for you @daniloff200

**Comment by juicyarts** [comment]
Sorry for the delay.  I managed to have a look this weekend and could not yet find out why the tests fail here. In the docs it (nearly) works as expected. I'll see if i can make the tests pass in the upcoming days.

**Comment by daniloff200** [comment]
@juicyarts  hey!
Thanks for your work! No worries about terms :) :100:

**Comment by daniloff200** [comment]
it's kinda abandoned now
Gonna close this for now, in case of any activity / work on that, ping me to reopen it

**Comment by juicyarts** [comment]
closed in favor of #6322 and desscendants

**Pull request closed without merging**
