### PR TITLE
I have created new component of name sideBarAccount

### PR DESCRIPTION
**Pull request by parasgulati**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [ ] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by parasgulati** [comment]
Most of the projects required different account handling. So sidebarAccount  component will provide pre-build bootstrap side Nav for them.

**Comment by daniloff200** [comment]
hello, @parasgulati !
Can you give more about such type of component? I can't find a lot info about what sideBarAccount is
Also, please, add some demo, like we have for other components in ngx-bootstrap, to show users , how to use your component

Also, I see, that travis build has a lot of errors. Could you fix them, please?

**Comment by parasgulati** [comment]
I have made changes in Docs for the sidebarAccount component. Please see.

**Review by parasgulati — COMMENTED** [review]
please see the changes in the docs and let me know.

**Pull request closed without merging**
