### PR TITLE
fix(tooltip): added missing position absolute to tooltip container

### PR DESCRIPTION
**Pull request by andreasdorfer**
The problem is described here: https://github.com/valor-software/ngx-bootstrap/issues/6492
Basically a position: absolute is missing for the wrapping component.

See a comparison of the generated styles by bare bootstrap and ngx-bootstrap:

bootstrap style on opened tooltip:
    will-change: transform;
    position: absolute;
    transform: translate3d(279px, 1952px, 0px);
    top: 0px;
    left: 0px;

ngx-bootstrap style on opened tooltip:
    will-change: transform;
    top: 0px;
    left: 0px;
    transform: translate3d(1129px, -37px, 0px);

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@valorkin why is no one checking PRs? is the project dead?

**Comment by valorkin** [comment]
Hey, long time))
@SvetlanaMuravlova please check this out

**Comment by SvetlanaMuravlova** [comment]
@FrancescoBorzi, hi)) the project isn't dead, your pr was missed, sorry.  Thank you for your work,  but it works little incorrectly, it need little more changes. Any way position isn't missed, it was included in bootstrap styles up to version 5.1.x, then there was some changes in version 5.2.x
So we need check compatibility with the latest version of bootstrap, i will add it

cc @valorkin

**Comment by SvetlanaMuravlova** [comment]
> @valorkin why is no one checking PRs? is the project dead?

thank you for your work, but full pr with fixies is here, so i will close this one is it ok, for you?  https://github.com/valor-software/ngx-bootstrap/pull/6543

**Comment by andreasdorfer** [comment]
Thank you, I close it.

**Pull request closed without merging**
