### PR TITLE
feat(datepicker): Add optional "today" button

### LINKED ISSUE #5680: Today Date Button
How can i add today date button to bsDatePicke that user can easily select today date.
Thanks

### PR DESCRIPTION
**Pull request by pjlinn**
Add button for user to easily set today's date. Samples heavily from, and finishes closed PR: https://github.com/valor-software/ngx-bootstrap/pull/5024

Potentially resolves https://github.com/valor-software/ngx-bootstrap/issues/5680

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by daniloff200** [comment]
I'm not sure, maybe I did something wrong, but, I wasn't able to see the button.
The same case, as it was for #5024, but, there was no demo at all.  Here we have it, but, it looks like it doesn't work correctly

Does it work for you @pjlinn  ?

Selection_023

**Comment by pjlinn** [comment]
Hey @daniloff200 , thanks for reviewing. I pulled in latest development and re-ran locally and it seems to be working. Screen shot taken after running the steps: 
```
npm run build.watch // in first terminal
ng serve // in second
```

Is there a better command to verify it is working locally?

Screen Shot 2020-06-15 at 9 22 29 AM

**Comment by daniloff200** [comment]
That's strange, I just completely rebuild all the app, and now it works
haha
 :rofl:  :smile: 
Well, looks good in general, I have an idea to make a positioning for this button, like, center,left,right

Gonna add some param for that later, and merge that

Thanks for your help, @pjlinn !!!

**Review by daniloff200 — DISMISSED** [review]

**Comment by pjlinn** [comment]
No worries! Thank you again for the review (and ngx-bootstrap in general) 👍

Good idea about position.

**Review by daniloff200 — APPROVED** [review]

**Pull request merged**
