### PR TITLE
feat(datepicker): disable specified days of week

### PR DESCRIPTION
**Pull request by ahtshamraziq**
added `dayDisabled` prop that accepts an array of integers (0=Sunday, ..., 6=Saturday) and disables the corresponding days of the week.

### CODE REVIEW

**Comment by ralzinov** [comment]
Anybody know is that PR would be merged?

**Review by valorkin — APPROVED** [review]

**Comment by YevheniiaMazur** [comment]
tested, looks good

**Comment by valorkin** [comment]
thanks a lot! :)

**Comment by KartikShankarappa** [comment]
@valorkin , What if we want to disable specific dates in each month ?
For eg: I want to disable all the dates in all months and in all the years except 15th and 20th of each month.
Right now, the current version of datapicker gives us the `datesEnabled` and `datesDisabled` properties. But that would mean I will have to calculate such dates myself. Also it would force me to put a Min and Max date between which i will have to calculate the enabled and/or disabled dates.
How about a function that will help us to enable or disable specific dates ?
Something similar to [this](https://ng-bootstrap.github.io/#/components/datepicker/overview#limiting-dates)

**Pull request merged**
