### PR TITLE
fix(common): fix next ver issue with moduleWithProviders

### PR DESCRIPTION
**Pull request by daniloff200**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

# Description

Fixes error in next version (Angular 10 pre-releases): 

```
Building collapse module
Error: Command failed: /bin/sh -c rimraf dist/collapse && node scripts/ng-packagr/api ../../src/collapse/package.json
ERROR: src/collapse/collapse.module.ts:10:21 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
10   static forRoot(): ModuleWithProviders {
                       ~~~~~~~~~~~~~~~~~~~
Error: src/collapse/collapse.module.ts:10:21 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
10   static forRoot(): ModuleWithProviders {
                       ~~~~~~~~~~~~~~~~~~~
    at Object.<anonymous> (/home/travis/build/valor-software/ngx-bootstrap/node_modules/ng-packagr/lib/ngc/compile-source-files.js:82:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/valor-software/ngx-bootstrap/node_modules/ng-packagr/lib/ngc/compile-source-files.js:5:58)
Building Angular Package
```

related to https://github.com/angular/angular/pull/36892

### CODE REVIEW

**Review by valorkin — APPROVED** [review]

**Comment by CemAltel** [comment]
When will this change be released? The 5.6.2 version causes a compilation error with Angular 10.

**Comment by gmaggiodev** [comment]
As workaround, waiting for release (https://github.com/valor-software/ngx-bootstrap/issues/5831#issuecomment-652389863)

**Comment by pavankjadda** [comment]
@gmaggiodev I see latest tag `5.7.0` in Github but NPM has latest version `5.6.1`? Why is that? Is it publishing error? And also I see `5.7.0` and `5.6.1` as tags but not releases in Github.

**Comment by gmaggiodev** [comment]
@pavankjadda I think it is yet in development branch. So, still not available, from my understanding.

image

**Comment by azherf** [comment]
Hey, just checking out if there is any update on this ?

**Pull request merged**
