### PR TITLE
feat(datepicker): add daterangepicker inline

### LINKED ISSUE #5303: Daterangepicker in inline mode.
### Bug description or feature request:
Add daterangepicker inline component.

### PR DESCRIPTION
**Pull request by Mikiawm**
Closes #5303

Daterangepicker in inline mode. 
Added component + simple test. 
Added new component in demos.

### CODE REVIEW

**Review by cshouts-tasc — DISMISSED** [review]
Code looks good. Unit tests pass. Tested the new component by hand with Chrome v75 on MacOS and it works well.

**Review by Domainv — DISMISSED** [review]

**Comment by ludmilanesvitiy** [comment]
1. need to fix placement on middle/small screens
Screenshot from 2019-09-11 14-44-56
2. Better to change menu name from "Inline Datepicker / Daterangepicker" to "Inline"

TODO (for @ludmilanesvitiy ) - after fix above, recheck inline datepicker spec (cy can't click due to overlapping)

**Review by Domainv — APPROVED** [review]

**Comment by Domainv** [comment]
fixed

**Comment by ludmilanesvitiy** [comment]
Retested, looks good.

**Pull request merged**
