### PR TITLE
feat(popover): add delay option (#5389)

### PR DESCRIPTION
**Pull request by amiram**
Closes(#5389) 

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [X] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [X] built and tested the changes locally.
 - [X] added/updated tests.
 - [X] added/updated API documentation.
 - [X] added/updated demos.

### CODE REVIEW

**Comment by amiram** [comment]
What's the status of merging pull requests to this repo? I see there are more waiting.

**Comment by daniloff200** [comment]
hey, @amiram , I will look at it at the nearest time, tomorrow, or, on Monday
Thank you for your contribution!

**Review by daniloff200 — APPROVED** [review]

**Comment by amiram** [comment]
@daniloff200 Thanks. This code is actually a copy-paste from existing delay feature in tooltip.

**Review by valorkin — APPROVED** [review]

**Comment by dmitry-zhemchugov** [comment]
I have tested this PR. Works as expected. Ready to merge.

**Pull request merged**
