### PR TITLE
fix(typeahead): fix focus after leaving control

### PR DESCRIPTION
**Pull request by tarusin**
Related to: #1884
Added new demo with input which demonstrates behavior with closed dropdown when we leaving input field.

### CODE REVIEW

**Comment by Domainv** [comment]
code coverage

**Comment by milosdanilov** [comment]
@tarusin @Domainv Is this going to be merged soon?

**Comment by Domainv** [comment]
@milosdanilov Not sure, the PR require improvements

**Comment by ejasarevic** [comment]
Any progress/plan for this PR?

**Comment by daniloff200** [comment]
@EmanJasarevic oh, that's pretty old one
I hope to have time to look at it, and rework soon. Let's hope that it will be available in next or next two releases

**Comment by ejasarevic** [comment]
Hi @daniloff200,
thanks for making these changes. However, IMO it still behaves differently than expected (even demo example https://valor-software.com/ngx-bootstrap/#/typeahead#cancel-on-focus-lost).
Here are a couple of use cases which I've tested, correct me if I have wrong expectations:
1. Start typing something (e.g "Wash") and wait for the async data to be loaded
Expected: Data loaded properly, all good.
Result: ✔️ 
2. Start typing "Wash" and pres tab a couple of times to move the focus from typeahead:
Expected: Typeahead will cancel async request and not load suggestions ("Washington" in this case).
Result: ➖ 
3. Start typing "Wash" and click outside of the input:
Expected: Typeahead will cancel async request and not load suggestions ("Washington" in this case).
Result: ➖ 

In our app we use the typeahead to provide suggestions, but also allow user to enter freetext in the input as well and accept it even though it is not option from the typeahead. For example, You start typing "Wash." and press enter/tab, focus will move to the next control and your input will be accepted. Is it doable with the current Typeahead implementation?

Regards

**Comment by chanageller** [comment]
@daniloff200
This still seems to be broken. cancelRequestOnFocusLost is always set to false.
There seems to be a bug in the code, when assigning the variables with the config settings the naming is wrong.

line 189 in typeahead directive-

      {
        typeaheadHideResultsOnBlur: config.hideResultsOnBlur,
        typeaheadCancelRequestOnFocusLost: config.cancelRequestOnFocusLost,
        typeaheadSelectFirstItem: config.selectFirstItem,
        typeaheadIsFirstItemActive: config.isFirstItemActive,
        typeaheadMinLength: config.minLength,
        adaptivePosition: config.adaptivePosition,
        isAnimated: config.isAnimated
      }
    );`
**typeaheadCancelRequestOnFocusLost** should be **cancelRequestOnFocusLost**

**Comment by daniloff200** [comment]
woah
@chanageller  can you submit a PR with that, and then we can check that?

**Pull request merged**
