### PR TITLE
refactor(common): migrate to angular 7

### LINKED ISSUE #5064: Support Angular 8 beta
### Feature request:

Make ngx-bootstrap compile with Angular 8 beta. Currently, timepicker's import causes an error:

ERROR in node_modules/ngx-bootstrap/timepicker/models/index.d.ts(3,22): error TS2307: Cannot find module '@angular/core/src/type'.

Should import from @angular/core, and not @angular/core/src/type.

### Versions of ngx-bootstrap, Angular:

ngx-bootstrap: 3.3.0

Angular: 8.0.0-beta.3

### PR DESCRIPTION
**Pull request by Domainv**
Closes #5064

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by ludmilanesvitiy** [comment]
Looks pretty well, all test scope (bs3,bs4) passed. Nice to have: build + unit-test check info travis CI for angular 6. And update of rxjs.

**Comment by Domainv** [comment]
Added next step to CI, step with Angular 6 (min step) skipped for now.
Because we should refactor build process on CI to get the opportunity for testing library built on Angular 7 be used with an app built on Angular 6

**Comment by ludmilanesvitiy** [comment]
This PR at all looks good, but not clear what PR should be merged first: or this either PR with CI update.

**Comment by ludmilanesvitiy** [comment]
Smoke tested in CHrome, tests passed. LGTM.

**Review by ludmilanesvitiy — DISMISSED** [review]

**Review by ludmilanesvitiy — APPROVED** [review]

**Pull request merged**
