### PR TITLE
fix(dropdown): add small delay for animation, to avoid issue with ngFor

### LINKED ISSUE #5727: Lose height of <ul> with ngFor in Dropdown component
Simple dropdown component ->
```
<div class="btn-group mt-2 float-right" dropdown>
    <button id="button-animated" dropdownToggle type="button" class="btn btn-alternate dropdown-toggle"
            aria-controls="dropdown-animated" >{{buttonCategoryTitle}} <span class="caret"></span>
    </button>
    <ul id="dropdown-animated" *dropdownMenu class="dropdown-menu dropdown-menu-right" role="menu" (click)="onDropdownCategory($event)" aria-labelledby="button-animated">
      <li role="menuitem"><a class="dropdown-item">test</a></li>
    </ul>
  </div>
```
which looks like
image
And after adding *ngFor -> 
```
<div class="btn-group mt-2 float-right" dropdown>
    <button id="button-animated" dropdownToggle type="button" class="btn btn-alternate dropdown-toggle"
            aria-controls="dropdown-animated" >button <span class="caret"></span>
    </button>
    <ul id="dropdown-animated" *dropdownMenu class="dropdown-menu dropdown-menu-right" role="menu" (click)="onDropdownCategory($event)" aria-labelledby="button-animated">
      <li role="menuitem" *ngFor="let category of this.categories"><a class="dropdown-item" [id]="category.id">{{category.title}}</a></li>
    </ul>
  </div>
```
and it looks ->
image
If we inspect element.. we see that there are 8 elements in list
image
and looks like ->
dropdown
Version ngx-bootstrap^5.5.0

### PR DESCRIPTION
**Pull request by daniloff200**
fixes #5727 
fixes #5687

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@daniloff200 thanks for the PR. It would be nice if you could add a test case that catches this bug, so it can't show up again in the future.

**Review by IraErshova — APPROVED** [review]

**Comment by daniloff200** [comment]
@FrancescoBorzi  we're gonna rework the e2e tests scope in the nearest future, so, will add this case for it too

**Comment by FrancescoBorzi** [comment]
good job @daniloff200 !

**Comment by Dassderdie** [comment]
@daniloff200
Is this also a fix for 
https://github.com/valor-software/ngx-bootstrap/issues/5602 ?

**Pull request merged**
